### ISSUE TITLE
Planned change to a GitHub/npm org - Naming

### ISSUE THREAD

**Issue by d-fischer** [twurple/twurple#194]
I'm planning to rename all libraries on npm and put them under an NPM @scope.
In the same step, it makes sense to also move to an org on GitHub.

The end result would be:
- GitHub org XXX
- GitHub repo XXX/XXX and XXX/XXX.github.io (for docs)
- npm packages @XXX/auth, @XXX/chat, @XXX/pubsub, ...
- The npm org name may be different from the GitHub org name - I'm trying to not use a "js" suffix for the npm org, but it's fine on GitHub

I have a few ideas:

- twirljs (username "twirl", which would have been my favorite, is taken on both npm and GitHub - meh because see above)
- tpi (is taken on GitHub, would be "tpijs" here) Downside: very close to [tmi.js](https://github.com/tmijs/tmi.js) in naming)

I would like to hear more ideas from the community before I decide.

**Comment by that1estonian** [comment]
tapi? 🤔

**Comment by d-fischer** [comment]
> tapi? 🤔

This sounds like [an ancient telephony API from Microsoft.](https://en.wikipedia.org/wiki/Telephony_Application_Programming_Interface).
It's also already taken on npm.

**Comment by that1estonian** [comment]
Damn. Kinda had a nice sound to it.

**Comment by that1estonian** [comment]
How about "classics" like ttvjs or ttvlib?

**Comment by d-fischer** [comment]
> ttvjs
No, I'm trying to avoid the "js" suffix.
> ttvlib
No, for similar reasons - this also sounds like stating the obvious for me.

---

On Discord there was a proposal I quite like:
"twurple"

The name is secured on npm and GitHub and I will probably use it - unless someone proposes a better one.

**Comment by citycide** [comment]
I like naming things, so here's a few ideas:

| name | GitHub | npm |
| --- | :---: | :---: |
| `twitcheroo` | ❌ | ✔ |
| `twitchback` (like switchback rail - "back and forth") | ✔ | ✔ |
| `tattlevee` (tattle + TV) | ✔ | ✔ |

**Comment by d-fischer** [comment]
I'm going with "twurple" - thanks for all the input!

**Comment by d-fischer** [comment]
Renamed, this repo is self-evident and the 5.0 prereleases already live under the new name 😄

**Comment by ylemkimon** [comment]
I wonder whether the renaming was requested by Twitch or decided on your own.
