### ISSUE TITLE
Custom Logging

### ISSUE THREAD

**Issue by some1chan** [twurple/twurple#205]
## Feature Request

Allow an option for outputting the log messages from the library into a custom logging solution (ex. Winston).

I really would like this feature, so I'm willing to dedicate some development time into this. I'm not too familiar with contributing code though.

**Comment by d-fischer** [comment]
As of v5.0.0-pre.12, you can pass the `custom` option into anything that accepts logger options like this:

```js
const chat = new ChatClient(auth, {
  logger: {
    custom: (level, message) => logWithYourOwnLogger(level, message)
  }
});
```

More in-depth documentation will probably follow in the upcoming week.
