### ISSUE TITLE
Add filters to helix.eventSub.getSubscriptions()

### ISSUE THREAD

**Issue by billygerhard** [twurple/twurple#246]
## Feature Request

Twitch added filters to <https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions> and Possible Leak™ will be adding more (user_id).

**Comment by d-fischer** [comment]
Will probably do this together with #242.

**Comment by d-fischer** [comment]
I added separate methods instead of adding filters to the existing method, since I generally use this as a method to prevent shooting oneself in the foot whenever filters are mutually exclusive. This will be part of 4.6 already which is due soon:tm:.
