### ISSUE TITLE
Implement EventSub channel.moderator.add/remove

### ISSUE THREAD

**Issue by AlcaDesign** [twurple/twurple#250]
### `channel.moderator.add`
- Subscription https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelmoderatoradd
- Event https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-moderator-add-event
### `channel.moderator.remove`
- Subscription https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelmoderatorremove
- Event https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-moderator-remove-event

**Comment by d-fischer** [comment]
Fixed that two weeks ago as well (see above) - closing.
