### ISSUE TITLE
Access to unknown URL/method

### ISSUE THREAD

**Issue by Knoot** [twurple/twurple#258]
### Actual Behavior
stops working after 1h - 1h 30m
`twitch-webhooks WARNING Access to unknown URL/method attempted: GET /`
After receiving this message in the console, listening no longer works.
This only happens on the remote server, with local tests everything is fine. Remote Ubuntu 20.04 64bit if it matters.
What can I do to find out the real reason for this?

### listener
```js
//local
const listener = new WebHookListener(client, new NgrokAdapter(), { hookValidity: 60 });
```
```js
//remote
const listener = new WebHookListener(client, new SimpleAdapter({
    hostName: config.remote.host,
    listenerPort: config.remote.port
}));
```
I tried using `new WebHookListener(client, new NgrokAdapter(), { hookValidity: 60 })` on a remote server, but that didn't change anything.

errors:
`twitch-webhooks WARNING Access to unknown URL/method attempted: POST /_ignition/execute-solution`
`twitch-webhooks WARNING Verification of unknown hook attempted: login.action`

### Environment

- Version: 4.5.5
- Node version: 14.16.1
- Operating system: Ubuntu 20.04 64bit

**Comment by d-fischer** [comment]
These warning messages just mean that something that is not Twitch is trying to access your WebHook service. It can happen at any time as web scrapers will just try pretty much random URLs, but it shouldn't impede functionality of your hooks at all.
