### ISSUE TITLE
Add Helix "Manage Held AutoMod Messages"

### ISSUE THREAD

**Issue by AlcaDesign** [twurple/twurple#259]
## Feature Request

A new endpoint (and scope `moderator:manage:automod`) has been added - https://dev.twitch.tv/docs/api/reference#manage-held-automod-messages

`POST 'https://api.twitch.tv/helix/moderation/automod/message'`

**Comment by d-fischer** [comment]
Fixed in 16a01d20 - missed tagging it. Will be part of the 4.6.0 release.
