### ISSUE TITLE
Improve documentation on when the chat client is ready

### ISSUE THREAD

**Issue by ThePooN** [twurple/twurple#263]
note: the FAQ URL mentioned at the beginning of the template is dead.

### Code

The following commit work-arounds this issue: https://git.cartooncraft.fr/osufrlive/bot/-/commit/3e62cc7f8e03becb0cefc8bd4e1854e313c9c29e

### Expected behavior

Being able to join channels manually right after connection, without necessarily using client options (tl;dr leaving it to the lib user).

### Actual Behavior

Fails after reaching a 10 seconds timeout.

### Environment

- Version: 4.5.5
- Node version: v14.16.0 & v16.2.0
- Operating system: Arch Linux, Alpine (inside Docker)

**Comment by d-fischer** [comment]
`onConnect` is too early since it's before authentication. Please use the `onRegister` event instead.

Leaving this open since the events could use some better documentation (in the main docs, not the reference part).

**Comment by d-fischer** [comment]
In the [new docs](https://twurple.js.org/docs/getting-data/chat/listening-to-events.html) this is now sufficiently explained IMO.
