### ISSUE TITLE
RefreshableAuthProvider throws Invalid token supplied on expired accessToken

### ISSUE THREAD

**Issue by smashboy** [twurple/twurple#264]
## Bug Report

Hi! I've setup `RefreshableAuthProvider` and when I pass expired accessToken from my db it always thorws an error `InvalidTokenError: Invalid token supplied.` I've tried manually to update token with util func `refreshUserToken()` and it is updating fine, so I don't think it is a problem related to twitch api. Looks like RefreshableAuthProvider is not receiving or loosing refreshToken, because if I call `getAccessToken()` after AuthProvider initialization it is not there.

![image](https://user-images.githubusercontent.com/30213662/120897511-4054e480-c62f-11eb-9350-d8e4e92f368c.png)

```ts
 console.log("INITIAL AUTH DATA:", auth);

 const p = twitchAuthProvider(auth);

 const t = await p.getAccessToken(twitchAuthConfig.scope);

 console.log("REFRESH TOKEN:", t?.refreshToken);
```

### Code

```ts
const twitchAuthProvider = ({
  accessToken,
  refreshToken,
  expiryDate,
  userId,
  broadcasterId,
}: TwitchAuthProviderType) => {
  return new RefreshableAuthProvider(
    new StaticAuthProvider(process.env.TWITCH_CLIENT_ID as string, accessToken),
    {
      clientSecret: process.env.TWITCH_CLIENT_SECRET as string,
      refreshToken,
      expiry: expiryDate ? expiryDate : null,
      onRefresh: async ({ accessToken, refreshToken, expiryDate }) => {
        await db.twitchIntegration.upsert({
          where: {
            userId,
          },
          create: {
            broadcasterId,
            token: accessToken,
            refreshToken,
            expiresAt: expiryDate,
            user: {
              connect: {
                id: userId,
              },
            },
          },
          update: {
            token: accessToken,
            refreshToken,
            expiresAt: expiryDate,
          },
        });
      },
    }
  );
};
```

### Expected behavior

Should automatically refresh accessToken

### Actual Behavior

Throws an error: `InvalidTokenError: Invalid token supplied`

### Environment

- Version: 4.5.5

**Comment by d-fischer** [comment]
This is a known problem with the scope fetching. This can't be fixed without breaking backwards compatibility, but there are multiple possible workarounds:

- Pass the scope in the constructor
- Refresh the token manually with the `refreshUserToken` function from `twitch-auth`
- Upgrade to the 5.0 prerelease (`@twurple/*`) and use the new `RefreshingAuthProvider` class which should handle this correctly.

Closing as it's already fixed (see last point above).
