### ISSUE TITLE
PubSubClient's onRedemption stopped working

### ISSUE THREAD

**Issue by reneolivo** [twurple/twurple#266]
## Bug Report

PubSubClient's onRedemption stopped working without any changes to the code. I used this example for authentication and getting the access and refresh tokens: https://github.com/twitchdev/authentication-node-sample

All was working fine, I could test the `onRedemption` listener by going to my own chat and selecting rewards. The reward message would be complete with all the details for the reward selected, the user who triggered, icons, etc.

I started my app again the other day and reward events are not longer being triggered.

### Code

```ts
passport.use('twitch', new OAuth2Strategy({
    authorizationURL: 'https://id.twitch.tv/oauth2/authorize',
    tokenURL: 'https://id.twitch.tv/oauth2/token',
    clientID: TWITCH_CLIENT_ID,
    clientSecret: TWITCH_SECRET,
    callbackURL: CALLBACK_URL,
    state: true
  },
  async function(accessToken, refreshToken, profile, done) {
    profile.accessToken = accessToken;
    profile.refreshToken = refreshToken;

    const authProvider = new StaticAuthProvider(
      process.env.TWITCH_CLIENT,
      profile.accessToken
    );
    const apiClient = new ApiClient({ authProvider });

    const pubSubClient = new PubSubClient();
    const userId = await pubSubClient.registerUserListener(apiClient);

    console.log('user ID works:', userId);
    pubSubClient.onRedemption(userId, (message) => {
      console.log('Never triggers', message);
    });

    done(null, profile);
  }
));
```

### Expected behavior

`pubSubClient.onRedemption` should trigger the callback when a reward is selected by any user.

### Actual Behavior

`pubSubClient.onRedemption` does not trigger

### Environment

- Version: 4.5.5
- Node version: 15.12
- Browser version: Chrome latest
- Operating system: Windows (runs through Ubuntu integration)

**Comment by d-fischer** [comment]
I can't reproduce this on my machine. The only thing I changed was that I reused the `TWITCH_CLIENT_ID` instead of the env variable which you used and which is different from the one used in the strategy initializer.

Please:
- make sure that the env var is filled
- make sure that the env var contains the same client ID as you use in the strategy
- if you still can't find a problem with your code, try enabling debug logging and come back with the output (redact any tokens that may appear):
```js
const pubSubClient = new PubSubClient(new BasicPubSubClient({ logger: { minLevel: 'debug' } }));
```

**Comment by reneolivo** [comment]
Thanks a lot, @d-fischer . I tried again using the debugger. This is what I'm getting:

```
node_1  | [2021-07-03T19:18:47.730Z] ℹ️  twitch-pubsub-client INFO Connecting...
node_1  | [2021-07-03T19:18:47.736Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:47.737Z] ℹ️  twitch-pubsub-client INFO Retrying in 1 seconds
node_1  | [2021-07-03T19:18:48.738Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:48.738Z] ℹ️  twitch-pubsub-client INFO Retrying in 1 seconds
node_1  | [2021-07-03T19:18:49.738Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:49.739Z] ℹ️  twitch-pubsub-client INFO Retrying in 2 seconds
node_1  | [2021-07-03T19:18:51.740Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:51.740Z] ℹ️  twitch-pubsub-client INFO Retrying in 3 seconds
node_1  | [2021-07-03T19:18:54.742Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:54.743Z] ℹ️  twitch-pubsub-client INFO Retrying in 5 seconds
node_1  | [2021-07-03T19:18:59.748Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:18:59.749Z] ℹ️  twitch-pubsub-client INFO Retrying in 8 seconds
node_1  | [2021-07-03T19:19:07.757Z] ℹ️  twitch-pubsub-client INFO Trying to reconnect
node_1  | [2021-07-03T19:19:07.757Z] ℹ️  twitch-pubsub-client INFO Retrying in 13 seconds
```

This is a bit weird since it was working as normal before. I don't use a firewall. The only "interesting" thing is that I'm running the code through docker.

Do you have any idea why the connection can't be made?

I believe that if a connection can't be made, it should throw a very visible error message.

**Comment by d-fischer** [comment]
Are you sure you're including standard error here? This looks like it only contains standard output, which does not contain anything above info severity. Errors should be thrown on any connection problem.

How to capture standard error is different for every Docker image. Consult your image's docs.

**Comment by d-fischer** [comment]
This issue is possibly fixed by a simple `yarn upgrade` or `npm upgrade`.

**Comment by reneolivo** [comment]
Will have a quick look. Thanks

**Comment by d-fischer** [comment]
Was this fixed? Can I close this?

**Comment by reneolivo** [comment]
Hello! I quickly checked and just got an error on a sub dependency. I had no time to dig deeper.

I'm out of town until Tuesday. Can you give me until then to confirm with all the details?

Thanks a lot!

**Comment by reneolivo** [comment]
Hello! It works! 🎉 

By upgrading to the latest release everything works fine. I'm not sure what the exact issue was, but updating it made everything work.

Thanks a lot.
