### ISSUE TITLE
Helix getStreams and getStreamsPaginiated methods are swaped?

### ISSUE THREAD

**Issue by song9446** [twurple/twurple#268]
### Code

https://github.com/twurple/twurple/blob/d363fb5edfd93c682aaa0a6a8bdb5bff03bf0347/packages/api/src/api/helix/stream/HelixStreamApi.ts#L95-L134

### Expected behavior

`getStreamsPaginated` should pass  `HelixPaginatedStreamFilter` type params.

### Actual Behavior

`getStreamsPaginated` is passing  `HelixStreamFilter` type params so it doesn't accept Pagination option params(such as `limit`)

### Environment

- Version: 
- Node version: 
- Browser version: 
- Operating system:

**Comment by d-fischer** [comment]
No, that is the exactly correct behavior.

You can pass things like `limit` and `cursor` to the non-paginated versions only. The paginated versions give you an object that helps you paginate through the results without handling these parameters.
