### ISSUE TITLE
Add resubgift and anonresubgift contexts to the PubSub package

### ISSUE THREAD

**Issue by CaveMobster** [twurple/twurple#270]
## Feature Request
I'd like to implement `resubgift` and `anonresubgift` contexts for the subscription message. Currently only `subgift` and `anonsubgift` are checked for, but it doesn't properly support multi month gift resubs.

**Comment by d-fischer** [comment]
Sure, go ahead, you can implement it on top of the `versions/4.6` branch.

**Comment by d-fischer** [comment]
Fixed by PR merge - thanks for your contribution!
