### ISSUE TITLE
EventSubListener won't take a RefreshingAuthProvider nor a Static one

### ISSUE THREAD

**Issue by eltharynd** [twurple/twurple#273]
## Feature Request

So if you try to create one it gives the following error
`EventSub requires app access tokens to work; please use the ClientCredentialsAuthProvider in your API client`
But from the twitch API docs it doesn't say anything about that... In fact some Listeners (such as `subscribeToChannelCheerEvents`) say you're supposed to authenticate as a user.. 

I think this is some misplaced logic on twurple. Or is there something I'm missing?

**Comment by d-fischer** [comment]
From <https://dev.twitch.tv/docs/eventsub>:

> You must include an app access token in all API requests. You do not need to include a user access token, even for subscriptions that require user authorization. This is because Twitch checks authorization throughout the lifetime of your subscription by calling Twitch’s internal authorization systems directly.

So this is perfectly intentional.

**Comment by eltharynd** [comment]
@d-fischer ok but the reason I tried to do that remains..
If i create a listener this way
```
Twitch.clientListener = new EventSubListener({
      apiClient: Twitch.client,
      adapter: new DirectConnectionAdapter({
        hostName: ENDPOINT.hostname,
        sslCert: {
          cert: `${fs.readFileSync(ENDPOINT.crt)}`,
          key: `${fs.readFileSync(ENDPOINT.key)}`,
        },
      }),
      secret: `${CREDENTIALS.channel}${Date.now()}`,
    })
```
Then when i try to subscribe to those kinds of events 
```
Twitch.clientListener.subscribeToChannelHypeTrainBeginEvents(Twitch.channelID, (event) => {
      console.log('subscribeToChannelHypeTrainBeginEvents')
      console.log(event)
    })
```
I get the following exception
```
HttpStatusCodeError: Encountered HTTP status code 403: Forbidden

Body:
{"error":"Forbidden","status":403,"message":"subscription missing proper authorization"}
```

**Comment by d-fischer** [comment]
EventSub works differently. You get through OAuth with the user with the required scope(s) (and possibly completely forget the token you got), then you subscribe to EventSub using an app token, and the Twitch authentication system will "remember" that the user went to OAuth with the necessary scopes. If you never requested the scopes for that user, you will get that authorization error.

**Comment by eltharynd** [comment]
Ok that's clear now thanks..

for future reference tho, my problem was that i was generating my accessToken with the account that created the app (which is a chat bot and moderator)... I had instead to log in to its app with my channel account....
Obviously, in retrospective....

Thanks and sorry to bother
