### ISSUE TITLE
ChatEmote.id returns NaN when parsed from TwitchPrivateMessage.parseEmotes()

### ISSUE THREAD

**Issue by Bauke** [twurple/twurple#275]
When doing `TwitchPrivateMessage.parseEmotes()`, the [ParsedMessageEmotePart](https://github.com/twurple/twurple/blob/versions/4.6/packages/twitch-chat-client/src/Toolkit/EmoteTools.ts#L23) you get have their ids defined as a `string`, while [ChatEmote](https://github.com/twurple/twurple/blob/versions/4.6/packages/twitch/src/API/Kraken/Chat/ChatEmote.ts)'s ids are `number`. This ends up making `ChatEmote.getUrl()` return NaN in the URL: `https://static-cdn.jtvnw.net/emoticons/v1/NaN/3.0`.

The [`parseInt`](https://github.com/twurple/twurple/blob/versions/4.6/packages/twitch-chat-client/src/Toolkit/EmoteTools.ts#L73) here is likely the culprit.

### Environment

- Version: 4.6.4
- Node version: 16.5.0

**Comment by d-fischer** [comment]
I implemented emotes v2 properly on the main branch and released it as version `5.0.0-pre.16`.
There will be no fix for this in the 4.x branch as it's backwards incompatible.
