### ISSUE TITLE
Extend base classes with JSON serialization

### ISSUE THREAD

**Issue by Satont** [twurple/twurple#276]
## Feature Request

Add something like `.toJSON()` for convert all fields to plain JSON and keep same interfaces everywhere. Can be helpful for build DTO without overhead.

**Comment by eltharynd** [comment]
#277

**Comment by d-fischer** [comment]
You're saying you want to build DTOs without overhead. But by saying that the library should help you with it, you move the overhead to the library code - and for *everyone who doesn't want to use it* as well.

Please extract the properties relevant to you by yourself.
