### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by lacksfish** [twurple/twurple#279]
Something about the versioning is off, making it impossible to resolve the packages due to a version missmatch

Snapshot from the npm debug logs

> ...
> 30 silly idealTree buildDeps
> 31 silly fetch manifest @twurple/api@*
> 32 http fetch GET 200 https://registry.npmjs.org/@twurple%2fapi 9ms (cache hit)
> 33 silly fetch manifest @twurple/auth@^5.0.0
> 34 http fetch GET 200 https://registry.npmjs.org/@twurple%2fauth 4ms (cache hit)
> 35 silly placeDep ROOT @twurple/api@5.0.0-pre.15 OK for: twitchStats@0.1.0 want: *
> 36 silly placeDep ROOT @twurple/auth@ OK for: @twurple/api@5.0.0-pre.15 want: ^5.0.0
> 37 warn ERESOLVE overriding peer dependency
> 38 warn Found: @twurple/auth@undefined
> 38 warn node_modules/@twurple/auth
> 38 warn
> 38 warn Could not resolve dependency:
> 38 warn peer @twurple/auth@"^5.0.0" from @twurple/api@5.0.0-pre.15
> 38 warn node_modules/@twurple/api
> 38 warn   @twurple/api@"*" from the root project
> 39 silly fetch manifest @d-fischer/cache-decorators@^3.0.0
> ...

Snapshot from console output (deleted node_modules beforehand

> $ npm install --save @twurple/auth @twurple/api
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: twitchStats@0.1.0
> npm ERR! Found: @twurple/auth@undefined
> npm ERR! node_modules/@twurple/auth
> npm ERR!   @twurple/auth@"*" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @twurple/auth@"^5.0.0" from @twurple/api@5.0.0-pre.15
> npm ERR! node_modules/@twurple/api
> npm ERR!   @twurple/api@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\myusername\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\myusername\AppData\Local\npm-cache\_logs\2021-08-11T08_48_06_846Z-debug.log
> 
>

**Comment by lacksfish** [comment]
I think the issue happens because @twurple/api has the following line in their package.json

>   "peerDependencies": {
>     "@twurple/auth": "^5.0.0"
>   },

Shouldn't this be

>   "peerDependencies": {
>     "@twurple/auth": "^5.0.0-pre.15"
>   },

**Comment by lacksfish** [comment]
Workaround:

`npm install @twurple/auth @twurple/api --force`

It's gonna spew error messages like a champ, but it is still gonna work and the two packages get resolved :)

**Comment by d-fischer** [comment]
The recommended workaround is:

```
npm install --legacy-peer-deps <packages>
```

This will be automatically mitigated on the final release of 5.0 and at some point after that I will implement measures that ensure it doesn't ever happen again.

**Comment by lacksfish** [comment]
Gotcha, noted. Really good library by the way, it's my go-to for Twitch now! I see Kraken API got phased out somewhere between pre8 and pre15 ? I guess it's because newly registered apps (as in, API creds) can no longer access those endpoints, right?

Cheers for all the work you put into this library :)

**Comment by d-fischer** [comment]
[Version 5.0.0-pre.13](https://github.com/twurple/twurple/releases/tag/v5.0.0-pre.13) removed it.
