### ISSUE TITLE
Additional chat client notices

### ISSUE THREAD

**Issue by CaveMobster** [twurple/twurple#288]
## Feature Request
I'd like to add a few new message notices to listen for in the `twitch-chat-client` package: 
- `bad_vip_max_vips_reached`
- `bad_vip_achievement_incomplete`
- `msg_channel_blocked`
- `msg_duplicate`
- `msg_emotonly`
- `msg_followersonly`
- `msg_followersonly_followed`
- `msg_followersonly_zero`
- `msg_followersonly`
- `msg_verified_email`
- `msg_timedout`

**Comment by d-fischer** [comment]
Sure, I don't see why they should be left out.

If you want to implement this, please make sure that for notices that can be responses to user-initiated commands, they should be resolving/rejecting the command's promise (see [this](https://github.com/twurple/twurple/blob/0f98ae6cb10fe60d4b3a9d08b027c05d80c06be9/packages/chat/src/ChatClient.ts#L1204-L1207) for an example).

Additionally, 4.x is now feature frozen and will only receive bug fixes. Please implement new features only on the `main` branch.
