### ISSUE TITLE
Accessing the cost of an eventSub subscription

### ISSUE THREAD

**Issue by serycodes** [twurple/twurple#298]
## Feature Request

Helix eventSub has a cost associated with each subscription. I'd like to PR this field in so I can access it from Twurple. Having the cost data available lets me see in advance who may have revoked their token, letting me take further action as needed.

(I've been modifying this locally to add it in for my purposes, but might as well PR it 👍 )

**Comment by d-fischer** [comment]
Sure, go for it.

**Comment by d-fischer** [comment]
Closed due to PR merge. Thanks for the contribution!
