### ISSUE TITLE
EventSubListener and Rewards not working as expected

### ISSUE THREAD

**Issue by Josyto** [twurple/twurple#306]
## Bug Report

The problem affects at least two methods of the EventSubListener class.

### Code

```ts
await TWITCH_EVENT_LISTENER.subscribeToChannelRedemptionAddEvents(
		USER.id,
		() => console.log('GENERIC')
	);
await TWITCH_EVENT_LISTENER.subscribeToChannelRedemptionAddEventsForReward(
		USER.id,
		'string with rewards id',
		() => console.log('ESPECIFIC')
	);	
```
### Expected behavior

- **subscribeToChannelRedemptionAddEventsForReward**: It should filter by ID and only run if it passes that filter, you should also be able to define multiple handlers, one for each id.

- **subscribeToChannelRedemptionAddEvents**: It should be executed when any reward is redeemed, be it custom or default

### Actual Behavior

- **subscribeToChannelRedemptionAddEventsForReward**: It should filter on the ID of the second parameter, but it does nothing. It only works with custom reward events, the default rewards do not work. In addition, only the last handler prevails, so if you try to put several, only the last one will be executed.

- **subscribeToChannelRedemptionAddEvents**: Only works with default rewards and only the last handler prevails

### Environment

- Version: 5.0.7
- Node version: 16.13.0
- Operating system: Windows 11

**Comment by Josyto** [comment]
Thanks for your answer.

I understand that the part that depends on Twitch is not possible to modify it.

Regarding the filtering part, I think it is a bug and not a feature. Since in the comments of the function it is described that it must filter, in addition the filter id is mandatory.

Attached capture of the source code
![image](https://user-images.githubusercontent.com/18529351/139875036-9e671e9e-6972-44f2-8607-0cb342f3fe8a.png)

**Comment by d-fischer** [comment]
I did just find a bug where creating both a filtered and an unfiltered subscription, or more than one filtered subscription, on the same listener may lead to events being passed to the wrong callback.

As a workaround: If you're only interested in a single custom reward, use the filtered version, if you need more than one (even if not all) use the unfiltered version and filter by reward ID by yourself for now.

**Comment by Josyto** [comment]
> I did just find a bug where creating both a filtered and an unfiltered subscription, or more than one filtered subscription, on the same listener may lead to events being passed to the wrong callback.
> 
> As a workaround: If you're only interested in a single custom reward, use the filtered version, if you need more than one (even if not all) use the unfiltered version and filter by reward ID by yourself for now.
> 
> By themselves, both forms work perfectly fine, I just tested it on my channel with two rewards. If listening for just one of them, the other one will not trigger. If listening for all, both will trigger. If listening for both of them, I _think_ both will be subscribed to, but the second callback receives both (I didn't explicitly test this last case)

I commented on it because the functions, although they can be used, gave rise to confusion with their descriptions
It is precisely that problem that I wanted to describe in this issue and the workaround is the one that I am using right now.

Thanks for the reply
