### ISSUE TITLE
API Client Check User Subscriptions JSDoc confusion

### ISSUE THREAD

**Issue by bradnak** [twurple/twurple#310]
## Bug Report
The JS Doc for the `ApIClient.subscriptions.checkUserSubscription()` method seems to be confused. The param `user` describes a broadcaster and the param `broadcaster` describes a user
![image](https://user-images.githubusercontent.com/3517352/141670561-d2b6fd1c-2b8c-4d53-b3c2-e7b1f10492a1.png)
I am using the parameters as per the actual parameter names from the method signature but the JSDoc may need updating.
I may be able to make a PR for this, but this is like a tiny change.
### Code

```ts
let someUserId = ''; // some user that subscribes to the channel
let someChannelId = ''; // a channel that the user subscribes to
// secrets refers to secret data loaded from file (which is gitignored)
let authProvider: RefreshingAuthProvider = new RefreshingAuthProvider({
    client_id: secrets.client_id,
    client_secret: secrets.client_secret
});
let apiclient: ApiClient = new ApiClient({authProvider: authProvider});
apiclient.subscriptions.checkUserSubscription(someUserId, someChannelId);
```

### Expected behavior

The JSDoc to be clear which parameter is which

### Actual Behavior

The JSDoc is confusing

### Environment

- Version: 5.0.9
- Node version: 16.9.1
- Operating system: Testing on Windows 10, running on Linux (AWS Amazon Linux 2)

**Comment by d-fischer** [comment]
It's not correct to classify this is a "bug", since there is no runtime problem with the code.
Rather, it's a documentation issue. The variable names are correct. I'll correct the descriptions as soon as I can.
