### ISSUE TITLE
Fusion onMessage and onAction events

### ISSUE THREAD

**Issue by BushedT** [twurple/twurple#311]
## Feature Request

Hello, 

I find it odd how these two events are handled. They send exactly the same data so merging the two would be a good thing in my opinion. It would allow to manage both events at the same time.

One thing that could be implemented is the addition of a boolean `isAction` exactly like `isCheer`.  This way it would just be a matter of checking this variable rather than having to handle both independently or having to create a common function that handles both. 

Thanks a lot !

T.

**Comment by d-fischer** [comment]
Hello and thanks for the suggestion!

The problem with this is that actions have a different format entirely that needs to be parsed out of a message, while cheers are only determined by the presence of a tag. These differences make the events incompatible to each other.

**Comment by BushedT** [comment]
You are welcome,

But I have a feel that this is an excuse out of laziness ngl, I have seen this behavior in multiple libs already like [go-twitch-irc](https://github.com/gempir/go-twitch-irc/blob/61d050bc6b6958e84422eab9364f1249196e1bcc/message.go#L236) or [tmi.js](https://github.com/tmijs/tmi.js/blob/df74e5dc8a13c3b732217654cd7bbca6873821f3/lib/client.js#L1069),  which they do not parse from an _entirely_ different format - comes from the exact same raw message - , neither does it make incompatible with current tags...
