### ISSUE TITLE
Wrong api endpoint for getFollowedStreamsPaginated

### ISSUE THREAD

**Issue by serg06** [twurple/twurple#312]
## Bug Report

`api.streams.getFollowedStreamsPaginated` gives a 404

### Code

```
url: 'stream/followed',
```

### Expected behavior

API doesn't give a 404

### Actual Behavior

API gives a 404

### Environment

- Version: 5.0.9
- Operating system: Windows

**Comment by d-fischer** [comment]
Merged and released in version 5.0.10. Dunno why this didn't autoclose.
