### ISSUE TITLE
New moderation API endpoints announced

### ISSUE THREAD

**Issue by serycodes** [twurple/twurple#314]
## Feature Request

New moderation API endpoints were announced today (in open beta).

https://discuss.dev.twitch.tv/t/new-moderation-api-endpoints-are-now-in-open-beta/34938

**Comment by d-fischer** [comment]
I generally wait until an endpoint is out of beta before implementing it. Therefore, I can not anticipate which version this will be part of.

**Comment by CaveMobster** [comment]
They're out of beta now! 🎉 I could implement them for 5.1 if that's okay? Unless @serycodes or you, @d-fischer, want to do it of course.

**Comment by CaveMobster** [comment]
@d-fischer While working on this, I saw that the Get Banned Events and Get Moderator Events endpoints [will be shut down on March 15th](https://discuss.dev.twitch.tv/t/deprecation-of-twitch-api-event-endpoints-that-supported-websub-based-webhooks/35137). Shall I mark them as deprecated and add that into this change, or should we get it into 5.0?

**Comment by d-fischer** [comment]
> @d-fischer While working on this, I saw that the Get Banned Events and Get Moderator Events endpoints [will be shut down on March 15th](https://discuss.dev.twitch.tv/t/deprecation-of-twitch-api-event-endpoints-that-supported-websub-based-webhooks/35137). Shall I mark them as deprecated and add that into this change, or should we get it into 5.0?

Things deprecated by Twitch can be marked as deprecated in the code at any point :) so I'd go for a deprecation for the next 5.0 patch instead.
For any other deprecations, I'd just add them in minor (or major) releases, not in patches. Twitch product deprecations are a special case though.

Feel free to ask questions like this in the Discord channel though! I want to move towards a more transparent development process, and that's one step towards this.

**Comment by CaveMobster** [comment]
@d-fischer Ah gotcha! And yes, good idea, I'll use the Discord from now on.

**Comment by d-fischer** [comment]
@CaveMobster Are you implementing the other endpoints (bans, blocked terms, chat settings) as well?

**Comment by CaveMobster** [comment]
> @CaveMobster Are you implementing the other endpoints (bans, blocked terms, chat settings) as well?

Yes. I planned on having it finished already but life got in the way. Apologies, will get to it as soon as I can.

**Comment by d-fischer** [comment]
No worries then, life always has priority 😅

**Comment by CaveMobster** [comment]
Well, life still hasn't calmed down it seems, so if anyone would like take this issue you're free to do so imo. I can be the backup for it, but it'll take at least a few more days, probably longer, for me to get in the right mindset again.

**Comment by zunderscore** [comment]
With my latest PR, that should cover the rest of the new moderation endpoints. I might try to add the chat settings endpoints as well, but I think that may be outside of the scope of this issue and could warrant a separate one. Thoughts?
