### ISSUE TITLE
Image url getters for HelixChannelSearchResult, HelixGame and HelixVideo

### ISSUE THREAD

**Issue by CaveMobster** [twurple/twurple#322]
## Feature Request
Hi again 😄

I noticed that `HelixChannelSearchResult`, `HelixGame` and `HelixVideo` don't have an image url getter like `HelixStream` does for the thumbnail url, but I think they're really useful. Shall I implement them?

**Comment by d-fischer** [comment]
The channel search returns non-templated profile picture URLs. For the rest, sure, you can go on and implement helper methods.

**Comment by CaveMobster** [comment]
My bad, the Twitch documentation says it returns variable dimensions, but it looks like the documentation is incorrect. 

I'll get the others done, thanks!
