### ISSUE TITLE
`bad_vip` notices don't get checked properly

### ISSUE THREAD

**Issue by CaveMobster** [twurple/twurple#325]
### Code
I added the following two notices in [`ChatClient.ts`](https://github.com/twurple/twurple/blob/5eab69eaaa7d4ff98ba8f7cdb37063059ddadb82/packages/chat/src/ChatClient.ts#L1394) a while ago:

```diff
+++	case 'bad_vip_achievement_incomplete':
+++	case 'bad_vip_max_vips_reached':
	case 'bad_vip_grantee_banned':
	case 'bad_vip_grantee_already_vip': {
		const match = content.split(' ');
		const user = /^\w+$/.test(match[0]) ? match[0] : undefined;
		if (user) {
			this.emit(this._onVipResult, channel, user, messageType);
		}
		break;
}
```

### Expected behavior
It should return an error when either all VIP slots are taken, or when the channel hasn't unlocked VIP slots yet.

### Actual Behavior
Because these two notices don't contain a username and `_onVipResult` requires a username to match, the Promise resolves instead of getting rejected.

### Environment

- Version: 5.0.9  (it's the same in the latest version though)
- Operating system: Windows 10

### Proposed solution
1. Create a new case in the switch statement for `bad_vip_achievement_incomplete` and `bad_vip_max_vips_reached`:
```ts
case 'bad_vip_achievement_incomplete':
case 'bad_vip_max_vips_reached': {
	this.emit(this._onVipResult, channel, undefined, messageType);
	break;
}
```

2. Make the username for `_onVipResult` optional.

I can implement this, as I've already debugged it for my own purposes.

**Comment by CaveMobster** [comment]
This has been fixed in https://github.com/twurple/twurple/commit/f61a0f66c64e501fe9cb2ab613d00b747f36a3aa.

**Comment by d-fischer** [comment]
Thanks! 🎉
