### ISSUE TITLE
Document how to use the Twitch CLI to test EventSub

### ISSUE THREAD

**Issue by d-fischer** [twurple/twurple#329]
It's a bit tricky to send testing payloads to the Twurple EventSub listener or middleware:

- The internal subscription ID is part of the URL
- The internal subscription ID is part of the secret, but might be cut off since the maximum length of a secret is 100

All of this should be documented properly on a new page of the documentation.

**Comment by Alex-D** [comment]
Example of Twitch CLI usage:
```cli
twitch event trigger subscribe \
-F https://example.com/event/channel.subscribe.42 \
-s channel.subscribe.42.yoursecret
```

Where `channel.subscribe.42` is the id of the EventSubSubscription returned by any `subscribeTo...` function.
And `yoursecret` is the secret passed at `EventSubListener` creation.

Example:
```ts
const secret = "yourSecret"
const listener = new EventSubListener({
  // ...
  secret,
})
const subscribeSubscription = await listener.subscribeToChannelSubscriptionEvents(channelId, e => {
	console.log(`new sub!`)
})

// Generate twitch CLI test command
console.log(
  'twitch event trigger subscribe',
  `-F https://example.com/event/${subscribeSubscription.id}`,
  `-s ${subscribeSubscription.id}.${secret}`.substring(0, 100)
)
```

Hope I'm right and helping other dev around :)
