### ISSUE TITLE
Add isFirstMessage property to TwitchPrivateMessage

### ISSUE THREAD

**Issue by dylanzemlin** [twurple/twurple#337]
## Feature Request

Last year Twitch added the `first-msg` tag to signify when a user sends their first message in a channel. This issue suggests that a isFirstMessage property is added to represent that tag.

I would be more than happy to quickly implement this and submit a pull request!

**Comment by d-fischer** [comment]
Seeing that this is currently not documented anywhere, I'd reject this for now, as I tend not to add any more undocumented stuff.

The Twitch chat docs are pending some big updates (the devs are teasing that there is a big overhaul going on), so ping me in this issue if this ever becomes "official" and I'll reopen the issue.
