### ISSUE TITLE
Make EventSubMiddleware.apply() synchronous

### ISSUE THREAD

**Issue by thomaslule** [twurple/twurple#338]
## Feature Request

`EventSubMiddleware.apply()` currently doesn't `await` anything and I believe it has no reason to do so in the future (as applying middlewares is a synchronous operation).

I think this method should be made synchronous, to let users prepare their express server synchronously.

Anyway, thanks for those amazing libs ❤️

**Comment by d-fischer** [comment]
Makes sense, but is technically a breaking change (because people could be using `.then()`). Will have to wait for a major version.
