### ISSUE TITLE
Pubsub channel subscription scope has changed

### ISSUE THREAD

**Issue by aetaric** [twurple/twurple#342]
## Bug Report

We (Twitch) have changed the pubsub scope for `channel-subscribe-events-v1.<channel ID>` from `channel_subscriptions` to `channel:read:subscriptions`. Twurple fails on a token with this scope. The current scope requirements for topics can be found here: https://dev.twitch.tv/docs/pubsub#topics

### Code

literally any code implementing pubsub for subscriptions

### Expected behavior

pubsub connection works

### Actual Behavior

The following output is from [nodecg-io-twitch-pubsub](https://github.com/codeoverflow-org/nodecg-io/blob/main/services/nodecg-io-twitch-pubsub/package.json):

```
[2022-03-26T00:27:30.565Z] ❌ twurple:pubsub ERROR Retrieving an access token failed: This token does not have the requested scopes (channel_subscriptions) and can not be upgraded.
If you need dynamically upgrading scopes, please implement the AuthProvider interface accordingly:

        https://twurple.js.org/reference/auth/interfaces/AuthProvider.html
[2022-03-26T00:27:30.566Z] ⚠️  twurple:pubsub WARNING No valid token available; trying to refresh
```

### Environment

- Version: 5.0.18
- Node version: v16.14.2
- Operating system: All

**Comment by iProdigy** [comment]
could just change to the new scope name [here](https://github.com/twurple/twurple/blob/main/packages/pubsub/src/SingleUserPubSubClient.ts#L168) and/or [this logic](https://github.com/twurple/twurple/blob/main/packages/auth/src/helpers.ts#L200) could be updated to accept equivalencies
