### ISSUE TITLE
RFC: AuthProvider rework

### ISSUE THREAD

**Issue by d-fischer** [twurple/twurple#344]
I've been thinking about how to make `AuthProvider`s better, and especially how to avoid creating many of them for most applications.

## Idea

The general idea would be that there would be one instance that can hold all user tokens and also (optionally) an app token.

Proposed new interface:

```ts
interface AuthProvider {
  /**
   * The client ID.
   */
  clientId: string;
  
  /**
   * The type of Authorization header to send. Defaults to "Bearer".
   */
  authorizationType?: string;

  /**
   * Fetches the current scopes for the given user.
   * 
   * @param user The user.
   */
  getCurrentScopesForUser: (user: UserIdResolvable) => string[];

  /**
   * Fetches a token for the given user.
   * 
   * @param user The user.
   * @param scopes The requested scopes.
   */
  getAccessTokenForUser: (user: UserIdResolvable, scopes?: string[]) => Promise<AccessToken | null>;

  /**
   * Fetches a token for a user identified by the given intent defined by the provider.
   * 
   * An intent is an arbitrary string that denotes a responsibility of a user's access token.
   * For example, having the "chat" intent means that the token will be used to connect to chat by default.
   * 
   * Intents are uniquely given to a single user, i.e. one intent can only be set to one user,
   * but one user can be used for multiple intents.
   * 
   * This is optional to implement, but required if you want to use the `ChatClient`,
   * as it accesses its connection credentials using an intent.
   * 
   * @param intent The intent to fetch a token for.
   * @param scopes The requested scopes.
   */
  getAccessTokenForIntent?: (intent: string, scopes?: string[]) => Promise<AccessTokenWithUserId | null>;

  /**
   * Fetches an app token.
   * 
   * Optional, for cases where you can't get a client secret in any way.
   */
  getAppAccessToken?: () => Promise<AccessToken | null>;

  /**
   * Fetches any token to use with a request that supports both user and app tokens,
   * i.e. public data relating to a user.
   * 
   * Useful for resources that are public, but where you app needs to access the data
   * in the context of the different users in order to not reach the rate limits for your app token.
   * 
   * If there is no user, this should probably return an app token,
   * but it can also return a user token in case you don't have access to app tokens.
   * 
   * @param user The user.
   */
  getAnyAccessToken: (user?: UserIdResolvable) => Promise<AccessToken | null>;

  /**
   * Requests that the provider fetches a new token from Twitch.
   *
   * This method is optional to implement. For some use cases,
   * it might not be desirable to e.g. ask the user to log in
   * again at just any time.
   * 
   * @param user The user.
   */
  refreshAccessTokenForUser?: (user: UserIdResolvable) => Promise<AccessToken | null>;
}

interface AccessTokenWithUserId extends AccessToken {
  /**
   * The ID of the user.
   */
  userId: string;
}
```

## Updates to the bundled `RefreshingAuthProvider`

```ts
class RefreshingAuthProvider implements AuthProvider {
  // ...

  /**
   * Adds a user to the provider.
   * 
   * Overwrites any intents that are already set to another user.
   */
  addUser(initialToken: AccessToken, intents?: string[]): string;

  /**
   * Adds intents to a user that was already added to the provider.
   * 
   * Overwrites any intents that are already set to another user, but keeps the previous intents for the given user.
   */
  addIntentsToUser(user: UserIdResolvable, intents: string[]): void;
}
```

## Advantages of this approach over the current one

- There is only one `AuthProvider` instance (and also only one `ApiClient` instance) in your application.
- By default, you don't have to worry about which user you want to request something on behalf of.

### `@twurple/api`

`@twurple/api` would automatically detect the correct user to use for an API request:
- For requests that require scopes, `getAccessTokenForUser` will be called, as it's the only method that can guarantee scopes.
- For requests that relate to a user, but *don't* require scopes, `getAnyAccessToken` will be called with that user's ID.
- For requests that don't relate to a user, `getAnyAccessToken` will be called without a user ID.
- You can override the context user, which will be used for each internal call to `getAnyAccessToken`, regardless of which user ID it is called with. This is especially useful with general endpoints that would be called very often and would completely drain an app access token's rate limit:

```ts
// ctx will have the same methods as a regular ApiClient, so you can use any of its methods
await apiClient.asUser(userId, async ctx => {
    // would normally get called using an app access token, but is overridden to use the given user token
    const badges = await ctx.chat.getGlobalBadges();
});
```

### `@twurple/chat`

The `ChatClient` would default to request the `chat` intent, which you can override using a configuration property named `authIntent`:

```ts
const authProvider = new AuthProvider();
authProvider.addUser(someAccessTokenData, ['botFor:125328655']);

// later...

const chatClient = new ChatClient({ authProvider, authIntent: `botFor:${channelId}` });
```

### `@twurple/pubsub`

The `PubSubClient` already uses a similar multi user interface, which would be replaced by this architecture, but should feel similar.

### `@twurple/eventsub`

Currently, there is only EventSub via a form of HTTPS WebHooks, which only ever uses an app access token.
However, the upcoming WebSocket transport could benefit from this - as it would use user access tokens, this new model would facilitate an easy switch from WebHooks to WebSockets (either for production or for having a different transport between prod/dev).

## Migration strategy

I think this design would cover all currently built-in use cases, but some of them might require major changes to their external interface.

- `StaticAuthProvider`: would stay the way it is to the outside, can be implemented using static returns on `getAnyAccessToken` and `getAccessTokenForUser`. Might lose the ability to house app access tokens. Other than that, there will most likely be no backwards compatibility breaks if you use this one.
- `RefreshingAuthProvider`: loses the second constructor parameter `initialToken`, instead gets a new method called `addUser` that requires a user ID and an initial token (like the constructor parameter was before - see further above in its dedicated section). The user ID would also be passed to the refresh callback so you can determine which user you need to save the credentials for. Should be able to be implemented without many changes. Instead of saving the access token object directly for one user, it would save its state in `Map` objects that map the user ID to its respective token. Because the client secret is already necessary to refresh tokens, this could very easily also generate app tokens, which the "any" method could fall back to as well.
- `ClientCredentialsAuthProvider`: not many changes. Generates app tokens whenever necessary, the methods just need to be renamed. Might also get a rename to something better like `AppTokenAuthProvider`. (bikeshedding proposals welcome)
- `ExtensionAuthProvider`: not many changes, very similar to the above, just different method to implement.
- `ElectronAuthProvider`: may gain the ability to authenticate multiple users via Electron's partitions feature later down the line, although I'm not 100% sure how that could work in practice.

This generally looks bright for custom implementations though! In most possible `AuthProvider` implementations, you'd just move some methods around and move the multi-user logic from a wrapper to the provider. Since I don't have an overview over all possible use cases though, please tell me if this design is missing something crucial.

**Comment by theca11** [comment]
Definitely sounds great. Some thoughts & questions:

- I'd make the fallback from user token to app token optional, and/or add an error/event/whatever notifying of this fallback. Having a backup is nice, but depending on the use case I can also see a potential disaster in which the app token hits the limits, because multiple people revoked their token and didn't bother to re-auth since everything keeps working. You may want to simply force the user to re-login before continuing.

- How would endpoints like `GET /users` or `GET /streams` determine the token to use? They accept user tokens but the call is not tied to a channel, so what user would the lib use for that if it has multiple stored?

- Any specific reason for the `StaticAuthProvider` to be kept as single-user? If not, I'd update it as the `RefreshingAuthProvider` (`addUser` function + `Map` of user/token instead of token in constructor). Even though it's not the optimal provider and probably not used much in complex multi-user apps, I think it would be more consistent with the rework in case anyone still wants to use it with a single `ApiClient`.

- Regarding the user to connect to chat with. Might not be the most elegant solution, but I'd directly add a `botId` param to the `ChatClient` constructor. I don't see a way to automatically determine which user/token is the desired in semi-complex scenarios. And even if there's a way, I'm not so sure that I'd feel comfortable letting the library make the decision because if something goes wrong the negative impact is potentially high.

  Example use case: let's say we have a chatbot service for multiple streamers, plus other tools. We have `[serviceBot, user1, ..., user50]` tokens. So far so good, because the only user with a token with scopes `chat:read`/`chat:edit` is the service bot. Now the service upgrades and allows the streamer to use their own custom bot name, which may be even their own account, and so we have `[serviceBot, user1, botUser1, user2, ..., user50]` tokens. I can't figure out how to automatically determine the token to use. And I definitely don't want the lib to use `botUser1` in `user50` channel by mistake and start writing there. Worst, imagine `user2` hooks their own account as bot, and we connect it to `user50`. Turns out `user50` sets up a certain command that answers with something bannable. Since it's `user2` the one writing in chat, he gets reported and banned by Twitch :confused:

**Comment by d-fischer** [comment]
>     * I'd make the fallback from user token to app token optional, and/or add an error/event/whatever notifying of this fallback. Having a backup is nice, but depending on the use case I can also see a potential disaster in which the app token hits the limits, because multiple people revoked their token and didn't bother to re-auth since everything keeps working. You may want to simply force the user to re-login before continuing.

Revoking tokens wouldn't remove them from the provider automatically. It would just lead to failure to call the endpoint, just like it does now.

>     * How would endpoints like `GET /users` or `GET /streams` determine the token to use? They accept user tokens but the call is not tied to a channel, so what user would the lib use for that if it has multiple stored?

By default it would use the "any token" strategy with no user set, so for most intents and purposes it would use an app token.
Maybe I can figure out a way to explicitly give context from the outside later.

>     * Any specific reason for the `StaticAuthProvider` to be kept as single-user? If not, I'd update it as the `RefreshingAuthProvider` (`addUser` function + `Map` of user/token instead of token in constructor). Even though it's not the optimal provider and probably not used much in complex multi-user apps, I think it would be more consistent with the rework in case anyone still wants to use it with a single `ApiClient`.

I don't see it being very useful for multiple users. If you're prototyping quickly or running on the frontend, you should only use a single user. For complex multi-user scenarios in the backend, you should always use `RefreshingAuthProvider` or create a custom implementation. If people want to use it with multiple users, they're still free to use it like they're doing right now - with multiple `ApiClient` instances.

>     * Regarding the user to connect to chat with. Might not be the most elegant solution, but I'd directly add a `botId` param to the `ChatClient` constructor. I don't see a way to automatically determine which user/token is the desired in semi-complex scenarios. And even if there's a way, I'm not so sure that I'd feel comfortable letting the library make the decision because if something goes wrong the negative impact is potentially high.
>       Example use case: let's say we have a chatbot service for multiple streamers, plus other tools. We have `[serviceBot, user1, ..., user50]` tokens. So far so good, because the only user with a token with scopes `chat:read`/`chat:edit` is the service bot. Now the service upgrades and allows the streamer to use their own custom bot name, which may be even their own account, and so we have `[serviceBot, user1, botUser1, user2, ..., user50]` tokens. I can't figure out how to automatically determine the token to use. And I definitely don't want the lib to use `botUser1` in `user50` channel by mistake and start writing there. Worst, imagine `user2` hooks their own account as bot, and we connect it to `user50`. Turns out `user50` sets up a certain command that answers with something bannable. Since it's `user2` the one writing in chat, he gets reported and banned by Twitch 😕

It might have been a little bit confusing, but I didn't mean to implement a way to _automatically_ determine the correct bot user.

Determining a token to use just by the scopes it has (or similar) can lead to detrimental mistakes, from using the wrong user to connect as a bot to disclosing data to people that should not have access to it, so this is an explicit non-goal.

For keeping relatively good ergonomics, my idea would be to add some kind of "tags" in the AuthProvider, which could be used for the chat client (and other external uses potentially?) to determine the appropriate token to use.

```ts
interface AuthProvider {
  // ...

  // adding a new optional method
  getAccessTokenForTag?: (tag: string) => Promise<AccessToken | null>;
}

class RefreshingAuthProvider implements AuthProvider {
  // ...

  // returns user ID for convenience, probably; overwrites any tags that are already present
  addUser(initialToken: AccessToken, tags?: string[]): string;

  // overwrites any tags that are already present, keeps the previous tags
  addTagsToUser(user: UserIdResolvable, tags: string[]): string;
}

interface ChatClientOptions {
  // ...

  // defaults to "chat", also falls back to "chat" if the given tag doesn't exist
  authTag?: string
}


// Usage:

const authProvider = new AuthProvider();
authProvider.addUser(someAccessTokenData, ['chat']);
const chatClient = new ChatClient({ authProvider });
// or:
const authProvider = new AuthProvider();
authProvider.addUser(someAccessTokenData, ['botFor:125328655']);
const chatClient = new ChatClient({ authProvider, authTag: `botFor:${channelId}` });
```

The `getAccessTokenForTag` method would be generally optional, but required for `ChatClient`, then.

**Comment by theca11** [comment]
> ```
> By default it would use the "any token" strategy with no user set, so for most intents and purposes it would use an app token. Maybe I can figure out a way to explicitly give context from the outside later.
> ```

But that kinda defeats the purpose of requesting user tokens to prevent app token rate limits in the first place. If you have 2000 user tokens and they all happen to hit general endpoints at the same time, your app token will get rate limited for no reason. And I can see people confused by hitting the limits even though they did what's supposed to be done, i.e. request each user a token

> ```
> I don't see it being very useful for multiple users. If you're prototyping quickly or running on the frontend, you should only use a single user. For complex multi-user scenarios in the backend, you should always use RefreshingAuthProvider or create a custom implementation. If people want to use it with multiple users, they're still free to use it like they're doing right now - with multiple ApiClient instances.
> ```

You're right, as I said I see it more of a consistency thing. Given how generally people find OAuth difficult by default, I'd expect extra questions regarding why a `StaticAuthProvider` can't be used for multiple users while the `RefreshingAuthProvider` can, it not being a limitation of the OAuth flow itself.

> ```
> It might have been a little bit confusing, but I didn't mean to implement a way to automatically determine the correct bot user.
> Determining a token to use just by the scopes it has (or similar) can lead to detrimental mistakes, from using the wrong user to connect as a bot to disclosing data to people that should not have access to it, so this is an explicit non-goal.
> For keeping relatively good ergonomics, my idea would be to add some kind of "tags" in the AuthProvider, which could be used for the chat client (and other external uses potentially?) to determine the appropriate token to use.
> ```

My bad, I implied the automatic part since you were talking about the `ApiClient` deciding which token to use for you. Glad to hear this was not the intention, clearly risky. Tags system sounds handy, more flexible than throwing in the id

**Comment by d-fischer** [comment]
> But that kinda defeats the purpose of requesting user tokens to prevent app token rate limits in the first place. If you have 2000 user tokens and they all happen to hit general endpoints at the same time, your app token will get rate limited for no reason. And I can see people confused by hitting the limits even though they did what's supposed to be done, i.e. request each user a token

You're absolutely right, but it's not possible to get a better *default* for this. If the endpoint is completely disjoint from the user that calls it, there is no way to get a user to call the endpoint as if you don't specifiy one manually in some way.

**Comment by billygerhard** [comment]
I like the idea of tagging. Would `getAccessTokenForTag` then grab a random access token from the access tokens tagged with that? Like if you had 10 "moderator" tokens, and you want to do a moderation task, but don't care which user?

**Comment by d-fischer** [comment]
> I like the idea of tagging. Would `getAccessTokenForTag` then grab a random access token from the access tokens tagged with that? Like if you had 10 "moderator" tokens, and you want to do a moderation task, but don't care which user?

No, tags would be unique. As the example says, existing tags with the same name are overwritten.

**Comment by billygerhard** [comment]
> Maybe a better name for it would be roles.

Yes, this would make it less confusing. Tags to me means I can add anything to anything at any time

**Comment by d-fischer** [comment]
I updated the initial post with the tags system (but named it "intents" instead), added a context switching API for the `ApiClient`, moved some stuff around, and made some other stuff more clear. Please re-check 🙂
