### ISSUE TITLE
Documentation for Auth providers has bad links

### ISSUE THREAD

**Issue by frozenfoxx** [twurple/twurple#346]
## Bug Report

On the [auth](https://github.com/twurple/twurple/blob/main/docs/auth/index.md) page the links are dead.

### Code

[Auth Index](https://github.com/twurple/twurple/blob/main/docs/auth/index.md)

### Expected behavior

All links to examples function.

### Actual Behavior

Links do not function.

### Environment

- Version: N/A
- Node version: N/A
- Browser version: N/A
- Operating system: N/A

**Comment by d-fischer** [comment]
You're looking at source files. They're not intended to be looked at directly. They're going through a build step on every push. 

The built documentation at https://twurple.js.org/docs/auth/ is fine.
