### ISSUE TITLE
Unrecognized notice ID: msg_timedout

### ISSUE THREAD

**Issue by beheh** [twurple/twurple#351]
### Code

This is from a closed-source chat bot, but mostly:

```typescript
	this.chatClient.onMessageFailed(this.onMessageFailed.bind(this));
	// [...]
	this.chatClient.say(channel, answer, {replyTo: msg.id})
```

### Expected behavior

`onMessageFailed` should be called

### Actual Behavior

The library logs the following message (not sure what's going on with the encoding, this is extracted from Cloudwatch):
```
⚠️ [43m[30mtwurple:chat:twitch[39m[49m [43m[30mWARNING[39m[49m [33mUnrecognized notice ID: 'msg_timedout'[39m
```

Looks like either the library has a typo, or Twitch changed this from what the existing code checks:

https://github.com/twurple/twurple/blob/925d38c454afe92696fd61c36bcff060be81b378/packages/chat/src/ChatClient.ts#L1524

[Twitch Documentation](https://dev.twitch.tv/docs/irc/msg-id) confirms it should be `msg_timedout` instead of `msg_timed_out`.

### Environment

- Version: `@twurple/chat@5.0.17`
- Node version: 12
- Operating system: Linux (running on AWS Fargate)

**Comment by d-fischer** [comment]
Thanks for reporting! I just released version 5.0.19 which includes a fix for this.
