### ISSUE TITLE
Changelog would be great

### ISSUE THREAD

**Issue by MR4online** [twurple/twurple#352]
## Feature Request

It would be great, if you could provide a simple changelog.
After updating @twurple/api I got an Typescript Error. Now I don't know if something important has changed or I can safely stay on the old version for some time.

Thanks a lot!

**Comment by d-fischer** [comment]
You mean the [releases page](https://github.com/twurple/twurple/releases)?

**Comment by MR4online** [comment]
perfect. thank you!
