### ISSUE TITLE
Support a configurable expiry grace period

### ISSUE THREAD

**Issue by kevmo314** [twurple/twurple#356]
## Feature Request

Right now, the expiry grace period is hardcoded: https://github.com/twurple/twurple/blob/450b0c71665bac91799a9e19921a3d1d3cea2890/packages/auth/src/AccessToken.ts#L44

It would be nice to be able to configure this. Specifically, I want to set it to a value dynamically calculated every time the expiration is checked.

We have two servers both using twurple/auth and if the expiry grace period is reached, they race each other and one ends up storing an invalid auth token. A simple way to mitigate this is to set the expiry to a fixed value + a random delay, that way it's unlikely the two race each other.

**Comment by d-fischer** [comment]
If this was random per request, it wouldn't prevent the race condition, it would just make it rarer.

The proper way to fix this kind of race condition would be a custom AuthProvider implementation that communicates between the servers, for example by storing some or all state (including some kind of lock for mutating operations like refreshes) in a shared storage like Redis.
