### ISSUE TITLE
Limit-Rater: Waiting because the rate limit was exceeded

### ISSUE THREAD

**Issue by arthurolmos** [twurple/twurple#358]
## Bug Report
Hello guys!  

Im getting this error since a 2 days ago: twurple:api:rate-limiter WARNING Waiting for 59512 ms because the rate limit was  exceeded.

I was testing a function that looped over the users from a team (about 40 users), and then would check if they were online. At one moment, it went into a loop and i started receiving status 429 - Too Many Requests. I dropped the site and fixed the code, but since then i wasn't able anymore to do any requests.

I'm using the API on a NextJS website hosted on Vercel.

How can i solve that?

### Code
```
async function getTeam() {
    try {
	const team = await apiClient.teams.getTeamByName(teamName);

	const users = await team?.getUserRelations();
	if (!users) return null;

	const allStreams = await Promise.all(
		users.map(async (user) => {
			return await (await user.getUser()).getStream();
		}),
	);
	const online = allStreams?.filter((stream) => !!stream);

	const rawTeam = team ? getRawData(team) : null;
	const rawOnline = online.map((stream) => {
		if (!stream) return null;

		const rawStream = getRawData(stream);
		rawStream.thumbnail_url = stream.getThumbnailUrl(384, 216);

		return rawStream;
	});

	return { team: rawTeam, online: rawOnline };
    } catch (err) {
	console.log({ err });
	return null;
    }
}
```

### Expected behavior

To be able to request API again.

### Actual Behavior

I get the error above as soon as I load the site, and am not able to do any requests.

### Environment

- Version: 5.0.18
- Node version: 16.14.0
- Operating system: Mac, Win

**Comment by d-fischer** [comment]
You're doing 81 requests every time this function is called. If you're running it more than 9 times a minute, that's the rate limit. It will apply across all people that visit the site. The client will wait until the rate limit resets for you to be able to make requests again.

Also, why did you move your question away from Discord? This issue tracker is not the place for usage questions.
