### ISSUE TITLE
Channel name must be lowercase to get chatters

### ISSUE THREAD

**Issue by samfundev** [twurple/twurple#364]
## Bug Report
To request the chatters from a channel, it looks like the channel name must be lowercase. Unfortunately, there's no official docs for this endpoint, but from using the endpoint it appears that this is the case. I would expect the library to lowercase all channel names before sending the request.

### Code
```ts
await apiClient.unsupported.getChatters("Twitch"); // error (Bad Request - 400)
await apiClient.unsupported.getChatters("twitch"); // success
```

### Expected behavior

The capitalization of the channel name should not matter.

### Actual Behavior

The channel name must be lowercase.

### Environment

- Version: @twurple/api: 5.1.6
- Operating system: Ubuntu 22.04

**Comment by d-fischer** [comment]
User names are always lower case. If you're passing something that is not a user name, the behavior is undefined. Therefore, this will not be fixed.

You should use user names and not - as you presumably do - display names. Display names might sometimes just be upper cased user names, but they might also be completely different, in which case this "fix" you sent will not help. Please make sure you always use user names.
