### ISSUE TITLE
Unsupported getChatters throws `Cannot read properties of undefined`

### ISSUE THREAD

**Issue by Satont** [twurple/twurple#379]
### Code
```ts
const users = await this.twitch.unsupported.getChatters(stream.user_name);
const chatters = users.allChatters
```

### Expected behavior

Should return list of usernames

### Actual Behavior

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'name')
at extractUserName (file:///app/node_modules/.pnpm/@twurple+common@5.1.6/node_modules/@twurple/common/es/userResolvers.mjs:23:51)
at UnsupportedApi.getChatters (file:///app/node_modules/.pnpm/@twurple+api@5.1.6_@twurple+auth@5.1.6/node_modules/@twurple/api/es/api/unsupported/UnsupportedApi.mjs:25:29)
at OnlineUsersService.onlineUsers (/app/apps/scheduler/src/online-users/online-users.service.ts:29:53)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Environment

- Version: `5.1.6`
- Node version: `18.6.0`

**Comment by Satont** [comment]
Sorry, used displayName instead of name.

**Comment by Satont** [comment]
Ok, maybe not.

**Comment by AlcaDesign** [comment]
Getting `Cannot read properties of undefined` from `extractUserName` means that you're passing in `undefined` to `getChatters`. You should check that `user_name` exists on `stream`. You might not have awaited `stream` and you're pulling `user_name` from a `Promise` object. That's the one bit you left out of your code which is critical for a complete answer.

**Comment by Satont** [comment]
> Getting `Cannot read properties of undefined` from `extractUserName` means that you're passing in `undefined` to `getChatters`. You should check that `user_name` exists on `stream`. You might not have awaited `stream` and you're pulling `user_name` from a `Promise` object. That's the one bit you left out of your code which is critical for a complete answer.

Thanks, issue not actually in unresovled promise, but in lib i'm used for fetch stream from redis. It returns me undefined field because i forgot to transform the redis object.
