### ISSUE TITLE
Disable auth token validity check

### ISSUE THREAD

**Issue by kevmo314** [twurple/twurple#390]
Can the oauth validity check be disabled? Or I guess alternatively: make a validate 429 not fail the authentication flow? I'm running into this error:

```
[2022-09-01T14:52:45.532Z] ❌ twurple:chat:twitch ERROR Retrieving an access token failed: Encountered HTTP status code 429: Too Many Requests

URL: validate
Method: GET
Body:
```

Which is happening because over 120 users joined in a short period of time: https://discuss.dev.twitch.tv/t/a-reminder-to-validate-access-tokens-when-using-oauth2/16218

Since we're using IRC chat, if the validity call is skipped the remainder of the API calls still seem to work.

**Comment by d-fischer** [comment]
This can't happen in a realistic usage scenario. This endpoint does not have any documented rate limit, so you'd have to be doing a *ton* of different user connections. This sounds like either a bug in your code or something really shady I don't want to support.

**Comment by kevmo314** [comment]
Our application is neither: we are using preemptible instances to monitor users' pubsub and occasionally an instance is preempted. A new one boots up and it takes over the old connections, leading to a very short burst of a few hundred connections and this library issues validation requests despite the token having a future expiry time.

Anyways, the antagonistic and haughty response here is unappreciated. We'll look elsewhere for quality libraries.

**Comment by d-fischer** [comment]
Interesting - in the log message it says you're using chat, not PubSub.

Other than that, all officially documented PubSub topics (except the automod related ones) are available via EventSub. I recommend you switch to that, as it's much easier to scale.
