### ISSUE TITLE
Update User Extension endpoint using `GET` instead of `PUT`

### ISSUE THREAD

**Issue by theca11** [twurple/twurple#392]
## Bug Report

[Update User Extensions endpoint](https://dev.twitch.tv/docs/api/reference#update-user-extensions) is missing `method: 'PUT'` and thus getting called instead with GET

https://github.com/twurple/twurple/blob/b28b0f2f2f0e52801caa18892ea4a28b015c5792/packages/api/src/api/helix/user/HelixUserApi.ts#L348-L356

Apart from that (which I could have PRed myself as it's trivial), note that it's missing `scopes` also. However, this one is a little tricky. Both `user:edit:broadcast` (mentioned in the API reference) and `channel:manage:extensions` (mentioned in the [scopes page](https://dev.twitch.tv/docs/authentication/scopes)) are valid scopes. In #343 support for scopes equivalencies was added, but they're defined in a `Map` and `user:edit:broadcast` is already linked to `channel:manage:broadcast`. So I don't know what approach (if any) you wanna take regarding scopes for this endpoint.

### Expected behavior

To send a PUT api call

### Actual Behavior

Sends a GET with body data, throwing back an error: `Request with GET/HEAD method cannot have body`

### Environment

- Version: 5.2
- Node version: 16.15.1
- Operating system: Win10

**Comment by zunderscore** [comment]
I imagine we would want to err on the side of the official documentation (https://dev.twitch.tv/docs/api/reference#update-user-extensions) and make it `user:edit:broadcast`.

**Comment by theca11** [comment]
The [scopes page](https://dev.twitch.tv/docs/authentication/scopes) is also official documentation
