### ISSUE TITLE
Add FFZ/BTTV emotes support

### ISSUE THREAD

**Issue by PasTrik** [twurple/twurple#401]
## Add FFZ/BTTV emotes support

Hello to all!
I had an idea that could help the management of emotes.

Streamers who are not affiliated (or more) with twitch don't have access to emotes.
The idea is to implement FFZ/BTTV emotes in the 
```ts
parseEmotes()
```

And type them like the basic emotes, when we do this function, we have the same type of object as the normal emotes.
```ts
 emote.displayInfo.getUrl({
          size: "3.0",
          animationSettings: "default",
          backgroundType: "light"
})
```

We could register the emotes to the ClientChat login and make a function :
```ts
async function refreshBttvEmotes()
```

> A guide for BTTV api : https://gist.github.com/chuckxD/377211b3dd3e8ca8dc505500938555eb

**Comment by d-fischer** [comment]
Third party emotes are conceptually completely different from regular Twitch emotes. You're gonna have to figure out the positions by yourself.

I do not intend to support this in the library as it's not directly a Twitch thing and also not useful for most bots.
