### ISSUE TITLE
Allow closing pubsub websockets

### ISSUE THREAD

**Issue by adarah** [twurple/twurple#410]
## Feature Request
I'm not sure if I missed it in the docs, but I couldn't find a way to close `@twurple/pubsub` SingleUserPubSub WebSockets.

My use-case for this is pretty simple:
I create a new PubSub connection when a certain React UI component is mounted, but I can't delete the connection once it unmounts, which leaves a lot of hanging/zombie WebSockets around.

An implementation like the `.quit()` method in `@twurple/chat` would solve this.

**Comment by d-fischer** [comment]
The solution to this is to remove all listeners from the client. Assuming that the underlying `BasicPubSubClient` doesn't have any topics left (which it shouldn't if you use `SingleUserPubSubClient` directly), it will then disconnect.

I added a new helper method for this, to be released with the next minor version, but you should be able to do it now by saving all return values from the `on*` methods to call `.remove()` on them.
