### ISSUE TITLE
Add support for new Shield Mode EventSub and Helix endpoints

### ISSUE THREAD

**Issue by jadamhall** [twurple/twurple#430]
Twitch has released Beta support for Shield Mode in EventSub and Helix endpoints.

EventSub -
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelshield_modebegin
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelshield_modeend

Helix - 
https://dev.twitch.tv/docs/api/reference#get-shield-mode-status
https://dev.twitch.tv/docs/api/reference#update-shield-mode-status

**Comment by zunderscore** [comment]
On it
