### ISSUE TITLE
pubsub: provide subscription duration for all contexts

### ISSUE THREAD

**Issue by StimulCross** [twurple/twurple#437]
## Feature Request

According to the [PubSub docs](https://dev.twitch.tv/docs/pubsub#receiving-messages), the subscription event can include the `multi_month_duration` field. You can find many examples of subscription messages with different contexts, including `sub`, `resub`, `subgift`, and `anonsubgift` that include or do not include this field in the payload.

The current implementation provides subscription duration only for gift contexts via `giftDuration` accessor.

My suggestion is to deprecate this method and create `subscriptionDuration` instead, which will provide subscription duration for all contexts.

```ts
/**
 * The duration of the gifted subscription, in months.
 *
 * Returns null if the subscription is not a gift.
 *
 * @deprecated Use {@link PubSubSubscriptionMessage#subscriptionDuration} instead.
 */
get giftDuration(): number | null {
	const data = this[rawDataSymbol];
	return data.context === 'subgift' ||
		data.context === 'resubgift' ||
		data.context === 'anonsubgift' ||
		data.context === 'anonresubgift'
		? data.multi_month_duration
		: null;
}

/**
 * The duration of subscription, in months.
 *
 * This refers to first-time subscriptions, auto-renewal subscriptions, re-subscriptions, or gifted subscriptions.
 * 
 * Defaults to 1.
 */
get subscriptionDuration(): number {
	return this[rawDataSymbol].multi_month_duration || 1;
}
```

Here I preferred to use `||` instead of `??` because there are very strange and elusive `resubgift` and `anonresubgift` events that include the field `"multi_month_duration": 0`. Here is the payload example: [https://github.com/twitchdev/issues/issues/181](https://github.com/twitchdev/issues/issues/181).

I could implement it if you approve this request.

**Comment by d-fischer** [comment]
I can see this, although I have a few comments on your suggestion:
- I'd plan it for 6.0 and skip the deprecation phase altogether.
- We're in the topical context of a subscription already, so the property can just be `duration`.
- "Defaults to" in a getter documentation makes no sense. It's only sensible for config objects with optional properties.
