### ISSUE TITLE
Add support for getting and setting tags

### ISSUE THREAD

**Issue by adleong** [twurple/twurple#445]
## Feature Request

The Helix Get Channel Info and Modify Channel Info endpoints now have a `tags` field to allow getting and setting tags:

https://dev.twitch.tv/docs/api/reference/#get-channel-information

Can we expose this new field through the HelixChannelApi?

**Comment by zunderscore** [comment]
This is already in 5.3.3 that just got released.

**Comment by adleong** [comment]
Fantastic, thank you!  I will try upgrading to 5.3.3.
