### ISSUE TITLE
Add support for new Shoutout features

### ISSUE THREAD

**Issue by jadamhall** [twurple/twurple#449]
## Feature Request

Twitch has added an API endpoint to create a Shoutout.
https://dev.twitch.tv/docs/api/reference/#send-a-shoutout

Twitch has created a new Shoutout EventSub subscription that sends notifications when the specified broadcaster sends a Shoutout.
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelshoutoutcreate

Twitch has created a new Shoutout EventSub subscription that sends notifications when the specified broadcaster receives a Shoutout.
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelshoutoutreceive

**Comment by zunderscore** [comment]
Working on this in #448
