### ISSUE TITLE
deleteChatMessages doesnt work with a username

### ISSUE THREAD

**Issue by NihilumPlays** [twurple/twurple#451]
in the docs: https://twurple.js.org/reference/api/classes/HelixModerationApi.html#deleteChatMessages it doesnt work if you usernames for the ids, only userids works

the twitch documentation also states that is has to be userids, not sure if thats relevant: https://dev.twitch.tv/docs/api/reference/#delete-chat-messages

**Comment by d-fischer** [comment]
Not a bug. Only IDs are supported. The type clearly says that it has to be an ID, and you can even hover over it in the documentation where it explicitly says that names will not work.
