### ISSUE TITLE
Feature Request: Allow EventSub WS consumers to attach listeners to onConnect/onDisconnect/onReconnect

### ISSUE THREAD

**Issue by adarah** [twurple/twurple#452]
I'm using Twurple in my frontend for EventSub Websocket subscriptions, and I'd like to be able to notify to the end user whether the websocket connection is functional.

Right now, after getting the confirmation that my connection+subscription was established, I change the UI to let the user know the program is ready to be used, but I have no way to inform them when  the connection was disrupted.

As a workaround, I'm listening to [offline events](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event) to let them know something went wrong and they might have to refresh the page, but since this library can already auto-reconnect+resubscribe (really nice QoL btw!), it would be more convenient for them if I just updated the UI when this reconnection happened.

**Comment by d-fischer** [comment]
In 6.0, each user gets a separate socket. Therefore this is a bit less trivial.

Would it make sense to fire the events with the user ID as parameter?

Also, I don't think I'd add `onReconnect`. Instead I'd just trigger another `onConnect` when reconnecting, as the underlying library already does the same.

**Comment by adarah** [comment]
I wasn't aware about there being multiple sockets. In that case, the library consumers would need to be able to identify which one lost connectivity. Since you said each user gets a separa socket, I think it makes sense to use the userId as a proxy for the socket identifier.

And not providing `onReconnect` is fine, I think that can be implemented on userland (would just be a flag like `wasAlreadyConnected` that gets checked on `onConnect`).

---
While we're on the topic of providing information to the end user, I noticed that in 6.0 I don't have a way to know if the subscriptions were established or not. There's `onSubscriptionCreateFailure` for failures, but there's no such equivalent for successes.
In 5.0 I could wait until the subscription promise resolved/reject to decide whether to show the end user. Would it also be possible to expose this "subscriptionCreateSuccess" event?

**Comment by adarah** [comment]
In hindsight, I think what I'm interested in is not the websocket state, but the subscriptions state. Knowing the websocket connection was opened but not knowing if the subscription went though is pretty much useless

**Comment by d-fischer** [comment]
1. Well, you still need a disconnect event to cover transitioning *to* that state from an existing established connection, even if you say you don't. I'm adding connect/disconnect events in the next patch.
2. I don't see the utility of adding a new event for this. On receiving a connect event, consider all existing subscriptions as "being recovered". New subscription objects are returned immediately (synchronously) when any EventSub subscription method is called.
3. Will be added.
4. Already exists as `onSubscriptionCreateFailure`, as you noticed. Also, another possible way to transition to this state (from "subscribed") would be `onRevoke`.
