### ISSUE TITLE
StreamNotLive error is not the only error Streams.createStreamMarker may throw

### ISSUE THREAD

**Issue by AdelaFoofur82** [twurple/twurple#454]
## Bug Report

On https://github.com/twurple/twurple/blob/versions/5.3/packages/api/src/api/helix/stream/HelixStreamApi.ts#L199 the only error the function throwns is StreamNotLive, but there are some other errors it may throw: https://dev.twitch.tv/docs/api/reference/#create-stream-marker. 

It's better to throw the error itself instead of using a middleware Error

**Comment by d-fischer** [comment]
This would be a breaking change, as people may rely on that error class being thrown.

Additionally, the premise of this is wrong, since all non-404 errors are still being re-thrown as normal.

**Comment by AdelaFoofur82** [comment]
No. I have receiving this error through a direct call to the API

{"error":"Not Found","status":404,"message":"code:\"VOD_NOT_READY\" message:\"Stream markers aren’t available during the first few seconds of a stream. Wait a few seconds and try again.\""}


And with twurple, the same call throws a Broadcast not live Error.

So I think it's important to throw the correct error
