### ISSUE TITLE
HellFreezesOverError: Socket for user xxxxx is not connected or does not have a session ID yet

### ISSUE THREAD

**Issue by adarah** [twurple/twurple#455]
## Bug Report
There's 2 bugs I want to report, and I think they are related:
1. When calling `.stop()` on an `EventSubWsListener` immediately after `.start()`, the library does not honor the `.stop()` call and attempts retrying opening the connection
2. After the the above finishes connecting, the HellFreezesOver error occurs. The connection seems to be dropped shortly after. No logs of this exit are shown

<img width="936" alt="image" src="https://user-images.githubusercontent.com/36046024/219908519-49331fbc-4733-470d-b74f-a5c13405cad9.png">

### Code
[Code Sandbox](https://codesandbox.io/s/cocky-galois-uml0nt?file=/src/App.js)
Not sure how familiar you are with React, but what's happening here is that the function inside the `useEffect` is being called immediately when the application starts, then the returned callback (the one with `.stop()`) is invoked, then first callback is invoked a second time. 

### Expected behavior
What should happen in the ideal world would be:
1. First connection starts being established
2. Gets aborted
3. A second connection is started

When invoking `.stop()` on a connection, the library should not attempt performing any sort of retrying, even if the connection has not been started yet. Not sure about the HellFreezesOver part, but I'm guessing that fixing the first issue should naturally lead to the second one never happening

### Actual Behavior
1. Invoking `.stop()` is not honored if it happens before the connection is established
2. HellFreezesOver is being thrown

### Environment

- Version: 5.3.4 and 6.0.0
- Node version: 18
- Browser version: Chrome
- Operating system: MacOS

Dunno about the sandbox environment but you should be able to inspect that one

**Comment by adarah** [comment]
I would also like to point out I see similar issues with `.stop()` not being honored in the ChatClient. Hopefully solving this for one of the libraries fixes it for the rest of them

**Comment by d-fischer** [comment]
> I would also like to point out I see similar issues with `.stop()` not being honored in the ChatClient. Hopefully solving this for one of the libraries fixes it for the rest of them

Could you maybe create a separate issue with a separate reproduction case for this?

**Comment by d-fischer** [comment]
I just published the package `@d-fischer/connection@8.0.1` which should fix this issue. You should be able to upgrade to this using a full upgrade, or if you don't want to do that, removing that specific package from your lock file and running your package manager's install command. I will not push *just* a dependency update as a new version.

Please confirm whether it worked for you. It *could* also fix the issue in `@twurple/chat`, although I have not tested that at all.

**Comment by adarah** [comment]
Thanks for the quick response! Upgrading to `@d-fischer/connection@8.0.1` fixed the issue for both the ChatClient and EventSubWS
