### ISSUE TITLE
"Uncaught ReferenceError: process is not defined" when using fresh Vite/CRA app

### ISSUE THREAD

**Issue by adarah** [twurple/twurple#457]
## Bug Report
I scaffolded a new vite app using the instructions in my reproduction repository README. Upon launching the application, I saw this error in the console:
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/36046024/220130489-b28098a2-c281-4906-a9fb-06259d99b29d.png">

### Code
[Reproduction repository](https://github.com/adarah/vite-bug-repro)
You can optionally run the project inside a devcontainer to have a fully identical environment

### Expected behavior
process.env should not be attempted to be accessed in a browser environment

### Actual Behavior
NodeLogger is being required, which accesses process.env

### Environment

- Version: 6.0.1
- Node version: 18
- Browser version: Chrome Version 110.0.5481.100 (Official Build) (arm64)
- Operating system: MacOS on host, but Linux inside the devcontainer

**Comment by adarah** [comment]
Oops, please ignore the quit logic related code, it probably is irrelevant to this specific issue; I was using it for another bug report I was reproducing

**Comment by adarah** [comment]
Apparently this also happens in a fresh CRA app. Does not happen on a fresh Next.js application though, so this probably explains why I had not run into this before

**Comment by d-fischer** [comment]
The package `@d-fischer/logger@4.2.1` contains a fix for this. I will make sure it gets required for the next patch version - for now you can just manually upgrade it. Please confirm.

**Comment by adarah** [comment]
Seems to have been fixed, thanks for the quick response time
