### ISSUE TITLE
HelixClipApi.createClip Does Not Respect User Context

### ISSUE THREAD

**Issue by Zozman** [twurple/twurple#458]
## Bug Report

When using twurple `6.0.1`, it seems that the [`createClip`](https://twurple.js.org/reference/api/classes/HelixClipApi.html#createClip) function does not respect swapping to a user context to create a clip and will always attempt to create a clip on behalf of the User returned to the [`channel`](https://twurple.js.org/reference/api/interfaces/HelixClipCreateParams.html#channel) property.

### Code

In this example, we have `twitchAsBotUser`, an `ApiClient` created using the following logic:

```javascript
const authTokenProvider = new RefreshingAuthProvider(
    {
      clientId: process.env.TWITCH_CLIENT_ID,
      clientSecret: process.env.TWITCH_CLIENT_SECRET,
      onRefresh: {...},
      },
    },
  );
authTokenProvider.addUser(process.env.TWITCH_BOT_ID, currentToken);
return new ApiClient({ authProvider: authTokenProvider });
```

Here, our `TWITCH_BOT_ID` is `528330225`.

We then attempt to use this `ApiClient` to create a clip of a channel (channel ID `26833307`) on behalf of `528330225` using the following logic:

```javascript
console.log(`Creating Clip Of Channel ${channelID} on behalf of user ${process.env.TWITCH_BOT_ID}`);
// First make the clip as the bot user
const clipId = await twitchAsBotUser.asUser(process.env.TWITCH_BOT_ID, async (ctx) => {
  return ctx.clips.createClip({
    channel: channelID,
    createAfterDelay: true,
  });
});
```

### Expected behavior

The expectation is that the `ApiClient` will attempt to create a clip of `26833307` as the user `528330225` using `528330225`'s token.

### Actual Behavior

According to the error, it appears that the function attempts to create a clip as `26833307`, which we do not have a token for and fails:

![image](https://user-images.githubusercontent.com/1192364/220207060-784945fe-d0a3-4e36-822c-b2170c880142.png)

The second line of the log states that it's scoped to `26833307` when I would expect it to be scoped to `528330225`.

In addition, I have attempted to set scopes to the `addUser` function as well using both the `clips` and `clips:edit` values to no avail.

Sure I'm just doing something dumb here, but at this point cannot figure out what.

### Environment

- Version: `6.0.1`
- Node version: `19.6.1`
- Browser version: Chrome 
- Operating system: Dockerized `NodeJs 19.6.1-alpine` container

**Comment by d-fischer** [comment]
Stream markers (both get and create) are also affected by this. Will fix tomorrow.
