### ISSUE TITLE
Unable to use userFollowsBroadcaster (deprecated endpoint)

### ISSUE THREAD

**Issue by zaytri** [twurple/twurple#461]
### Code

```ts
const isFollower = await apiClient.users.userFollowsBroadcaster('userId', 'broadcasterId')
```

### Expected behavior

The function uses the new endpoint `GET https://api.twitch.tv/helix/channels/followed` as detailed here: https://dev.twitch.tv/docs/api/reference/#get-followed-channels and successfully returns a boolean.

### Actual Behavior

The function is using the deprecated endpoint `GET https://api.twitch.tv/helix/users/follows` as detailed here: https://dev.twitch.tv/docs/api/reference/#get-users-follows and giving a 404 error because I'm using a client ID created after February 17, 2023. This endpoint will also be decommissioned on August 3, 2023.

### Environment

- Version: 6.0.1
- Node version: 18.13.0
- Browser version: Chrome 110.0.5481.105
- Operating system: Windows 11

**Comment by d-fischer** [comment]
The method will not be changed to use the new endpoint, as people who have used the endpoint before can still use it. Instead, there will be a new method.
