### ISSUE TITLE
Add option for default thumbnail dimensions; clarify HelixStream.thumbnailUrl formatting

### ISSUE THREAD

**Issue by tonyd33** [twurple/twurple#468]
## Feature Request

It would be a convenient addition to make it so that passing in empty `width, height` into `HelixStream.getThumbnailUrl()` would just return the url for default width and height in [HelixStream.getThumbnailUrl()](https://github.com/twurple/twurple/blob/97ab0db6a754300a5b9b7833db8d01921ad1bd87/packages/api/src/api/helix/stream/HelixStream.ts#L129)
```
return !width || !height
    // url for default dimensions
    ? this[rawDataSymbol].thumbnail_url.replace("-{width}-{height}", "")
    : this[rawDataSymbol].thumbnail_url
          .replace("{width}", width.toString())
          .replace("{height}", height.toString());
```
I currently do that manually because I don't really care about the thumbnail dimensions, but as a user, I'd appreciate the library taking care of that for me.

The other suggestion is regarding `HelixStream.thumbnailUrl`. It currently returns a url like `http://thumbnail.com/streamer-{width}-{height}.jpg`, and there wasn't any indication in the [twurple docs](https://twurple.js.org/reference/api/classes/HelixStream.html#thumbnailUrl) that you had to format it yourself.  This can't be changed to the proposed default url above anymore for backwards compatibility reasons, so I think the docs should make that more clear. Having the same description as the [official docs](https://dev.twitch.tv/docs/api/reference/#get-streams) would be nice so readers don't have to cross-reference it.

**Comment by d-fischer** [comment]
Is this way of getting the "default dimensions" documented anywhere? I don't like just including undocumented stuff, since it might go away at any given time.

I don't think it makes sense to use the docs text for the `thumbnailUrl` property, as people can just use the `getThumbnailUrl` method instead; I could just link to that.

**Comment by tonyd33** [comment]
> Is this way of getting the "default dimensions" documented anywhere? I don't like just including undocumented stuff, since it might go away at any given time.

You’re right, I thought the “default dimensions” behavior would’ve been documented somewhere, but it doesn’t actually seem to be. Scrap this idea then.

> I don't think it makes sense to use the docs text for the `thumbnailUrl` property, as people can just use the `getThumbnailUrl` method instead; I could just link to that.

A link the docs or some indication that you have to format `thumbnailUrl` yourself would be great since not everyone is familiar with the Twitch API and wouldn’t expect it from reading the twurple docs and would save just a bit of work.

Thanks for getting to this by the way. I know it’s a pain to reply to nitpicky issues like this but I suggest it because I appreciate this project.
