### ISSUE TITLE
`requestScopesForUser` with `ElectronAuthProvider` only requests first scope when given array

### ISSUE THREAD

**Issue by TGC79** [twurple/twurple#475]
## Bug Report
When passing an array of scopes to `requestScopesForUser` on `ApiClient` it seems to only request a scope for the first item in the array, and not all of them at once specifically when using `ElectronAuthProvider` as the provider.

### Code
```ts
const scopes = ['chat:read', 'chat:edit', 'bits:read', ...];
const provider = new ElectronAuthProvider({ clientId, redirectUri });
const client = new ApiClient({ authProvider: provider });
const user = await client.getTokenInfo();

await client.requestScopesForUser(user.userId, scopes);
const token = await this.provider.getAccessTokenForUser(user.userId);
console.log(token);
```

### Expected behavior
Expect a single scopes authorization prompt from `ElectronAuthProvider` asking for all scopes in the provided `scopes` array. The returned `token` should be authorized for all scopes provided to `requestScopesForUser`.

### Actual Behavior
The authorization prompt generated only asks for the first scope in `scopes`, and the returned `token` will only have one scope as well. Looping the `requestScopesForUser` call and providing it a single scope each time results in a `token` with all the requested scopes but creates a new electron authorization prompt for each request.

### Environment

- Version: 6.0.9
- Node version: 16.19.0
- Browser version: electron@21.4.3
- Operating system: Win10

**Comment by d-fischer** [comment]
Sadly, this can not be fixed without a breaking change of the `AuthProvider` interface - it's simply an oversight in the v6 `AuthProvider` design. So it can't be fixed for now, but I will think about a solution for v7.

**Comment by jendib** [comment]
You can workaround the issue by putting all scopes in one (space separated): `['openid user:read:subscriptions']`

**Comment by d-fischer** [comment]
This issue was fixed for all auth providers (as it was present everywhere), but as Twitch now enforces unsupported browsers (which Electron apparently is) to be unable to login, the `auth-electron` package was removed.

**Comment by TGC79** [comment]
@d-fischer I'm not seeing any issue with unsupported browser on twitch login within the electron prompts. I've removed the connection from my twitch account, logged out, logged in again, and authorized all the prompts successfully.

Am I missing something to reproduce?

> Version: 6.2.0
> Node version: 16.19.0
> Browser version: electron@24.1.3
> Operating system: Win10

**Comment by jendib** [comment]
I confirm, no issue here as well with an updated Electron. The "unsupported browser" warning only appear with older versions. More details here: https://help.twitch.tv/s/article/supported-browsers?language=en_US

**Comment by d-fischer** [comment]
> I confirm, no issue here as well with an updated Electron. The "unsupported browser" warning only appear with older versions. More details here: https://help.twitch.tv/s/article/supported-browsers?language=en_US

That is incorrect, I reproduced this yesterday using the latest version.

**Comment by jendib** [comment]
That's strange, I have an app currently in production using your lib and users can login fine. There must be something more to it.

**Comment by lclc98** [comment]
I believe it might not be completely enforced yet as I been doing similar auth stuff with webview(via tauri) and only 1 out of 5 Devs still work even with some matching versions of webview. But I'm not sure how they are enforcing it so it could be different

**Comment by d-fischer** [comment]
Related report: https://github.com/twurple/twurple/issues/503
