### ISSUE TITLE
ChatClient connection sharding

### ISSUE THREAD

**Issue by d-fischer** [twurple/twurple#479]
A ChatClient should be able to create and maintain multiple connections to Twitch's chat server based on a configurable maximum amount of channels per connection.

While it's theoretically possible to send messages to channels you have not joined on a connection, all outgoing messages should be routed to the correct connection for the channel in order to not overwhelm one connection's send queue.

**Comment by Reprevise** [comment]
What's the status of this?

**Comment by d-fischer** [comment]
I don't currently have time for this, sorry, will pick it back up soon-ish.

**Comment by d-fischer** [comment]
As Twitch announced that there will be chat over EventSub soon, and also that IRC will stop supporting large numbers of channels even across multiple connections, this does not make sense to add anymore.
