### ISSUE TITLE
pubsub: split generic mod action event into several specific ones

### ISSUE THREAD

**Issue by StimulCross** [twurple/twurple#491]
## Feature Request

Although the payload of the `chat_moderator_actions.<user_id>.<channel_id` topic is not documented at all, it includes various useful events that are definitely worth implementing separately, such as `ban`, `timeout`, `unban`, `untimeout`, etc. 

Some of the events are unique. For example, if end-users needs to know which particular restriction was removed from a chat user - a permanent ban or a timeout, they can easily listen for `unban` and `untimeout` events. There are also more detailed room state events, which include the moderator identities that changed the room state.

The generic interface looks like this:

```ts
export type PubSubModActionType =
	| 'ban'
	| 'unban'
	| 'timeout'
	| 'untimeout'
	| 'delete'
	| 'clear'
	| 'raid'
	| 'emoteonly'
	| 'emoteonlyoff'
	| 'followers'
	| 'followersoff'
	| 'subscribers'
	| 'subscribersoff'
	| 'r9kbeta'
	| 'r9kbetaoff'
	| 'slow'
	| 'slowoff';

export interface PubSubModActionMessageData {
	type: string;
	moderation_action: PubSubModActionType;
	args: [string, string?, string?] | null;
	created_by: string;
	created_by_user_id: string;
	created_at: string;
	msg_id: string;
	target_user_id: string;
	target_user_login: string;
	from_automod: boolean;
}
```

I think this will improve usability as the current `PubSubClient#onModAction` is not much friendly to use. So my suggestion is to create specific mod action events that seem to be stable enough (like the above ones) and keep the existing `PubSubClient#onModAction` to handle other mod action events.

A basic example of the slow-mode event:

```ts
export class PubSubBaseModActionEvent extends DataObject<PubSubModActionMessageData> {
	constructor(data: PubSubModActionMessageData, private readonly _channelId: string) {
		super(data);
	}

	get channelId(): string {
		return this._channelId;
	}

	get moderatorId(): string {
		return this[rawDataSymbol].created_by_user_id;
	}

	get moderatorName(): string {
		return this[rawDataSymbol].created_by;
	}
}

export class PubSubSlowModeEvent extends PubSubBaseModActionEvent {
        // This will be narrowed to `slow` and `slowoff` inside switch construction
	get enabled(): boolean {
		return this[rawDataSymbol].moderation_action === 'slow'
	}

        // 0 if disabled
	get duration(): number {
		return this[rawDataSymbol].args ? +this[rawDataSymbol].args[0] : 0;
	}
}
```

I wanted to implement this myself, but I'm not sure how best to do it with the current library structure. It's probably will be a major update. But at least I can help with investigating and sharing the exact payload of the mentioned above events. Let me know if you want to work on this.

**Comment by d-fischer** [comment]
This will be a job for more high level libraries. `@twurple/pubsub` is a rather low level library, and as such, it has a 1-to-1 mapping from Twitch PubSub topics to event handler methods.

It's definitely a thing to pursue in the future, but the `@twurple/pubsub` package is not the correct place for this.
