### ISSUE TITLE
UserNotice.message's type should be specified as optional

### ISSUE THREAD

**Issue by zaytri** [twurple/twurple#495]
### Code

I was trying to access `UserNotice.message` for every `UserNotice`, and noticed that it broke on raids.

```js
chatClient.onRaid((_, __, ___, notice) => {
  console.log(notice.message.value) // can't access value of undefined
})
```

Which confused me because TypeScript was telling me that wasn't possible.

And then with a better understanding of how Twitch sends user notices, I think `message` would only exist for user notices that are announcements or resubs? And doesn't exist for other user notices, but that wasn't clear without live testing it.

### Expected behavior

TypeScript warning given that `message` could be undefined.

### Actual Behavior

No warning, leading to me attempting to use that value without checking if `message` was defined and breaking a whole block of code.

### Environment

- Version: 6.1.0
- Node version: 18.13.0
- Browser version: Google Chrome 111.0.5563.147
- Operating system: Windows 11

**Comment by d-fischer** [comment]
Technically, you aren't even really supposed to use the `message` property directly, Instead you should be using the `msg.params` object, like `notice.params.message`. This will probably change in the next major.

I can't really fix this *before* the next major anyway, since it's technically a breaking change.

**Comment by zaytri** [comment]
Ah ok I didn't know it was possible to access like that since it doesn't show up in the type docs, thanks!

**Comment by d-fischer** [comment]
It will be `notice.text` for the next major. (It was renamed from `message` to `text` for disambiguation/consistency reasons.)
