### ISSUE TITLE
ElectronAuthProvider receives Unsupported Browser error when logging into Twitch

### ISSUE THREAD

**Issue by typeou** [twurple/twurple#503]
Recent Twitch-side change appears to have broken ElectronAuthProvider. Twitch no longer appears to consider Electron as a supported browser. Received reports of users being unable to log in and was able to replicate the issue myself after logging out.

Can log into Twitch normally via typical browser (Firefox Developer Edition 113.0b2) with no issues.

### Expected behavior

When ElectronAuthProvider requests the user to log in to their Twitch account and the user enters their information, the user is successfully logged in.

### Actual Behavior

When entering their information, Twitch replies that the browser is unsupported. User is thus unable to provide authorization to the Electron app.

### Environment

- Version: 6.1.1
- Electron version: 24.1.1
- Node version: 14.17.5
- Operating system: Windows 10 Home

**Comment by d-fischer** [comment]
That probably just means that the `ElectronAuthProvider` is broken without a possible fix. I have tried a simple user agent override and it didn't get around the check.
