### ISSUE TITLE
Hype Train Pubsub event

### ISSUE THREAD

**Issue by InzeNL** [twurple/twurple#508]
## Feature Request

Referencing [Twitch's EventSub Subscription Types documentation](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/).

I would be looking to implement this myself, but I'll touch on this later.

Creating this ticket in regards to the HypeTrain PubSub event. But there are move PubSub events that still need implementation. I can compile a list. I think the best approach on this would be to create separate feature requests for each generic pubsub topic (e.g. the hype train topic includes `channel.hype_train.begin`, `channel.hype_train.progress`, and `channel.hype_train.end`). But I'll have that open for discussion before I spam the issue tracker with feature requests.

As said, I'll be looking to implement the HypeTrain PubSub event myself. The other events, I may, depending on my time, but I can definitely create the requests for that, and perhaps let someone else work on it.

**Comment by iProdigy** [comment]
I think you're confusing eventsub and pubsub. Hype trains are not an official topic on pubsub, and hypetrains over eventsub is already implemented by twurple

**Comment by InzeNL** [comment]
I was absolutely misusing the terms. And somehow, I completely overlooked the hype_train implementation. Issue closed
