### ISSUE TITLE
Make `ebs-helper` compatible across different runtimes using `jose` instead of `jsonwebtoken`

### ISSUE THREAD

**Issue by AdrianGonz97** [twurple/twurple#509]
## Feature Request

`jsonwebtoken` unfortunately only works in Node so it'd be great to replace it with a jwt library that works across different runtimes like `jose`.

I already have a working implementation of this so that I would be able to use it with CF workers. I'd be more than happy to submit a PR for this change!

**Comment by d-fischer** [comment]
Sure, feel free to PR this onto the `main` branch. I don't think this is fit for a patch version.
