### ISSUE TITLE
Allow PubSubClient to accept AppTokenAuthProvider

### ISSUE THREAD

**Issue by plrs9816** [twurple/twurple#513]
## Feature Request

Some topics of the PubSubClient can be used with app access token, but currently it only accepts user auth provider:
it throws 'Can not get user access token for AppTokenAuthProvider'.

I think there should be way to use pubsub with app token.

**Comment by d-fischer** [comment]
This is an undocumented topic that is not officially supported, so there are no plans to specifically accommodate it.

The documentation stating "some topics require authentication" comes from a time when there were indeed officially supported topics without authentication, which is not the case anymore, and that part should probably be removed by Twitch.

Getting viewer counts is not a supported scenario by Twitch anyway, and the topic you're using may go away at any point in time without warning.
