### ISSUE TITLE
`EventSubWsListener#onStreamOnline` with `RefreshingAuthProvider` raises an access token error

### ISSUE THREAD

**Issue by fml09** [twurple/twurple#518]
### Code

```ts
  const tokenData = JSON.parse((await readFile('./tokens.json')).toString());
  const authProvider = new RefreshingAuthProvider({
    clientId: TWITCH_CLIENT_ID,
    clientSecret: TWITCH_CLIENT_SECRET,
  });
  authProvider.onRefresh(async (_, newTokenData) => {
    await writeFile(`./tokens.json`, JSON.stringify(newTokenData, null, 4));
  });
  await authProvider.addUserForToken(tokenData, ['chat']);
  const apiClient = new ApiClient({authProvider});
  const listener = new EventSubWsListener({apiClient});

  const user = await apiClient.users.getUserByName(TWITCH_STREAMER_NAME); // not your name. 
  if (!user) return;


  listener.onStreamOnline(user, async data => { // subscription failed because of the invalid token
    console.log(data, 'is live');
  });

  listener.onStreamOffline(user, async data => {
    console.log(data, 'is offline');
  });

  listener.start();
```

### Expected behavior

Whatever the auth provider we use, subscription for some streamer's online status should work fine.

### Actual Behavior

If we use the auth provider as the `RefreshAuthProvider`, an access token error occurs.

I guess the problem is caused by the `broadcaster` variable in `EventSubApi#subscribeToChannelUpdateEvents` being passed as the `userId` parameter of `Client#callApi`. 
https://github.com/twurple/twurple/blob/main/packages/api/src/endpoints/eventSub/HelixEventSubApi.ts#L334

### Environment

- Version: 7.0.0
- Node version: 18.16.1
- Operating system: MacOS M1 Pro

**Comment by d-fischer** [comment]
This is a design decision. There needs to be _some_ user ID passed, since Twitch requires a user access token to subscribe to any EventSub WebSocket topic, and as you can also not subscribe to events from multiple different users on the same socket, this is the only sensible way to get around these limitations consistently.
