### ISSUE TITLE
"This should never happen"

### ISSUE THREAD

**Issue by xFreakss** [twurple/twurple#523]
## Bug Report
![image](https://github.com/twurple/twurple/assets/89689590/6b6be9d3-76f9-49e6-b001-65eb7f945395)

### Code

```js
const clientId = process.env.TWITCH_CLIENT_ID;
const clientSecret = process.env.TWITCH_CLIENT_SECRET;

const authProvider = new AppTokenAuthProvider(clientId, clientSecret);

const apiClient = new ApiClient({ authProvider });

const listener = new EventSubWsListener({ apiClient });

listener.onStreamOnline('164181954', async e => {
  console.log(e.broadcasterDisplayName, "went live")
}).start();
```

### Expected behavior
Being notified on the streamer comes online.

### Actual Behavior
Red message.

### Environment

- Version: ![image](https://github.com/twurple/twurple/assets/89689590/e5e28c81-5438-47be-b5a3-f9217d404b1b)
- Node version: v20.5.1
- Operating system: 
![image](https://github.com/twurple/twurple/assets/89689590/39bdafd9-807a-44c2-97b1-98ee23eb279d)

**Comment by xFreakss** [comment]
The same happens with `StaticAuthProvider`

**Comment by zunderscore** [comment]
You must call `listener.start()` to establish the connection before you subscribe to events.

**Comment by xFreakss** [comment]
Thank you. The documentation says that the listener was supposed to start by itself

Got me another error: `Invalid Token Supplied` - I got mine from `https://dev.twitch.tv/console/apps/${{ApplicationID}}`

**Comment by jumoog** [comment]
You can't use an app access token.

> When subscribing to events using WebSockets, you must use a user access token only. The request fails if you use an app access token. The [Subscription Types](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types) topic lists the scope requirement for each event. If the event doesn’t specify a scope requirement, you must create a user access token with no scope.

https://dev.twitch.tv/docs/eventsub/manage-subscriptions/

**Comment by xFreakss** [comment]
Many thanks!
