### ISSUE TITLE
Trim tokens?

### ISSUE THREAD

**Issue by rodrigograca31** [twurple/twurple#528]
## Feature Request

Wherever tokens/client ids are taken trim them before usage? 🤔

Today I had to update my tokens in 7 files, i just used VS Code to replace all.
But after deploying the new code it wasnt working. Later I found out I had an extra space for some reason...
something like `const accessToken = "yar63fvr ";`

I'd like to suggest that the token or clientId would be trimmed before actual usage by `StaticAuthProvider` or other code... I know it was my fault but.......... thoughts?

**Comment by d-fischer** [comment]
It is not Twurple's job to sanitize your strings.
