### ISSUE TITLE
New event : viewermilestone

### ISSUE THREAD

**Issue by ShalltearFR** [twurple/twurple#529]
Hello,
I receive an error:
twurple:chat:twitch WARNING Unrecognized usernotice ID: viewermilestone.
I don't find any documentation about this new feature in Twitch API.

<img width="300" alt="01" src="https://github.com/twurple/twurple/assets/20574430/ebde0236-2576-4cc4-8be1-9f59874a56b5">

This event is triggered since the new addition of sharing the succession of streams watched.

<img width="206" alt="02" src="https://github.com/twurple/twurple/assets/20574430/54821621-7007-4f5f-bc76-b5c1426bed38">

**Comment by d-fischer** [comment]
Please set the log level to debug to send me a full raw line for this message, if possible.

**Comment by ShalltearFR** [comment]
what do you mean by "log level to debug" ?

**Comment by Ensiferum** [comment]
@d-fischer Here is additional info:
`[2023-11-24T10:07:59.359Z] 🐞 twurple:chat:irc DEBUG Received message: @badge-info=;badges=;color=#008000;display-name=stealth_cake;emotes=;flags=;id=632b432b-fa68-4dfa-977a-e0f44134dd4d;login=stealth_cake;mod=0;msg-id=viewermilestone;msg-param-category=watch-streak;msg-param-copoReward=450;msg-param-id=9eacf814-641d-4ea2-acd9-e6575c2ab5cc;msg-param-value=10;room-id=123364886;subscriber=0;system-msg=stealth_cake\swatched\s10\sconsecutive\sstreams\sthis\smonth\sand\ssparked\sa\swatch\sstreak!;tmi-sent-ts=1700820479250;user-id=65539496;user-type=;vip=0 :tmi.twitch.tv USERNOTICE #timofey
[2023-11-24T10:07:59.360Z] twurple:chat:twitch WARNING Unrecognized usernotice ID: viewermilestone`

**Comment by d-fischer** [comment]
Just saw that Twitch has currently [advertised](https://twitter.com/TwitchSupport/status/1725181874769650161) this as an "experiment", which can wildly change or even be removed without any notice. In fact, in that thread, they said that the feature has been there before in another version which has already been removed again. I will take care of this event (i.e. reopen this issue) as soon as Twitch officially declares this as not an experiment anymore (e.g. by adding it to the docs).
