### ISSUE TITLE
@d-fischer/cross-fetch Headers is not a constructor

### ISSUE THREAD

**Issue by pearrb1235** [twurple/twurple#531]
### Code

```ts
  const twurpleClient = new ApiClient({
    authProvider,
  });
  const tokenInfo = await twurpleClient.getTokenInfo();
  console.log(tokenInfo);
```

### Expected behavior

getTokenInfo method return `Promie<TokenInfo>` and no runtime error

### Actual Behavior

I use twurple api get token info on next.js, it has an error.
`Error: _d_fischer_cross_fetch__WEBPACK_IMPORTED_MODULE_2__.Headers is not a constructor`
![image](https://github.com/twurple/twurple/assets/47129048/eed3e8a5-b397-4427-9881-2aad225618c6)

next.js build `@d-fischer/cross-fetch/node-ponyfill.mjs` file to vendor-chunks folder.
```js
import nodeFetch from 'node-fetch'
export const Headers = nodeFetch.Headers
```
converted to
```js
var node_fetch__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! node-fetch */ \"(rsc)/./node_modules/node-fetch/lib/index.mjs\");
const Headers = node_fetch__WEBPACK_IMPORTED_MODULE_0__[\"default\"].Headers
```

`import "@d-fischer/cross-fetch"`(.mjs) has error but `require("@d-fischer/cross-fetch")`(.js) work well

### Environment

- Version:
```
  @twurple/api: 7.0.5
  @twurple/auth: 7.0.5
  next: 14.0.2
```
- Node version: v21.1.0
- Operating system: Windows_NT x64 10.0.19045

**Comment by d-fischer** [comment]
The screenshot says that your Next.js is out of date. Does this still happen when on the latest version?

**Comment by pearrb1235** [comment]
Next.js 14.0.3
The same error occurs.
![image](https://github.com/twurple/twurple/assets/47129048/b11bed54-264b-4326-8337-5e9e2b3f9060)

**Comment by d-fischer** [comment]
Can you try replacing the first line of the `node-ponyfill.mjs` file with this?

```js
import * as nodeFetch from 'node-fetch'
```

If that helps you (I don't have a Next project handy) I will land this fix in the actual package.

**Comment by pearrb1235** [comment]
> Can you try replacing the first line of the `node-ponyfill.mjs` file with this?
> 
> ```js
> import * as nodeFetch from 'node-fetch'
> ```
> 
> If that helps you (I don't have a Next project handy) I will land this fix in the actual package.

After replace `node-ponyfill.mjs` file, it work well.

**Comment by d-fischer** [comment]
Thanks for the cooperation - I published the update to the `@d-fischer/cross-fetch` package, to get it you can `npm upgrade` / `yarn upgrade` or if you want to make sure you only get this specific update, you should just be able to remove the specific entry for that package from your lock file.
