### ISSUE TITLE
Twurple Node Red Modules

### ISSUE THREAD

**Issue by royaltongue** [twurple/twurple#534]
## Feature Request

Considering that Twurple is already available through NPM, would it be possible to package it for Node Red? Specifically, I'm looking for the ability to interact with PubSub. 

I have been using [this flow](https://github.com/n3odym3/Node-RED_Twitch_EventSub), but it's not very reliable and often disconnects with no warning

**Comment by d-fischer** [comment]
This doesn't seem like just a packaging thing. It would require building and maintaining a huge environment-specific JSON file, which I'm not knowledgeable about (nor, frankly, interested in).

If you want to have an integration, you're probably better off writing it yourself.
