### ISSUE TITLE
Ngrok connection doesn't work anymore

### ISSUE THREAD

**Issue by iliass-bensalah** [twurple/twurple#537]
### Code

`connAdapter = new NgrokAdapter({
                port: 3200
  });`

### Expected behavior

Ngrok connection established

### Actual Behavior

Ngrok ended support for old clients, it now requires an api token to be passed on.

`twurple:eventsub CRITICAL Could not listen on port 3200: failed to connect session, Auth(Response("Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"))`

**Comment by d-fischer** [comment]
This is already in 7.0.7 - closing.
