### ISSUE TITLE
Add Get Moderated Channels endpoint

### ISSUE THREAD

**Issue by serycodes** [twurple/twurple#551]
## Feature Request

[Get Moderated Channels](https://dev.twitch.tv/docs/api/reference/#get-moderated-channels) has moved from public beta to v1.

I can probably PR it this weekend.

**Comment by zunderscore** [comment]
@serycodes Gotcha covered 👍

**Comment by serycodes** [comment]
> @serycodes Gotcha covered 👍

Thanks!
