### ISSUE TITLE
Unable to delete EventSubWS subscription (incorrect token type for api call)

### ISSUE THREAD

**Issue by theca11** [twurple/twurple#564]
## Bug Report

Trying to delete an EventSub WS subscription fails with error 404 Not Found:

```
Error deleting subscription to channel.chat.message.XXXXX.XXXXX Encountered HTTP 
status code 404: Not Found

URL: eventsub/subscriptions?id=686c94de-ec8e-4695-b1f6-395eed9c5a37
Method: DELETE
Body:
{"error":"Not Found","status":404,"message":"not found"}
```

Checking the code the issue seems to be that `deleteSubscription()` is calling the API endpoint with an app token. Similarly to the create subscription endpoint, the delete one requires an app token if the transport is webhooks, but a user token if the transport is websockets, and this is currently not handled.

I'll let you fix this one because I don't now how/where you'd like to handle the extra logic, since right now the method only requires the sub id and so the associated transport and userId need to be retrieved at some point.

### Code

Stumbled across this while trying to use `subscription.stop()`, but the underlying issue as I said is in `deleteSubscription()`
https://github.com/twurple/twurple/blob/2fb2abbf99c6d957b61d195a82eaae4b87c3cb18/packages/api/src/endpoints/eventSub/HelixEventSubApi.ts#L253-L262

Checked that the subscription existed before trying to delete it, and also checked with cURL that sending the request with the appropriate user token does succeed

### Expected behavior

To be able to delete EventSub websocket subscriptions

### Actual Behavior

Trying to delete subscriptions errors

### Environment

- Version: 7.1.0-pre.7
- Node version: v20.11
- Operating system: Windows 10

**Comment by d-fischer** [comment]
For people that use this directly via `@twurple/api`, it's hard to figure that out reliably. The expectation is that users force the context via `asUser` or `withoutUser`.

For people using `@twurple/eventsub-*` there will be a fix though, as these libs do have the necessary state.
