### ISSUE TITLE
Feature Request: Automod EventSub Message Subscription Types

### ISSUE THREAD

**Issue by navarr** [twurple/twurple#569]
## Feature Request

I'm using twurple for the Twitch portion of a multi-stream-chat combiner for the streamer.  One of the problems I'm noticing is that messages that are held back by automod are not shown to the streamer, even once they are approved!  I believe these messages are likely sent in the `automod.message.hold` and `automod.message.update` events.

It would be wonderful if I could bind to these events and use the same message processing logic that I use with `channel.chat.message`.

**Comment by d-fischer** [comment]
As far as I understand, the AutoMod EventSub messages are only sent to the chatting user's context, not the broadcaster context, so I don't think this would help your specific case. The issue you're having sounds more like a bug on Twitch's side.

Either way, the EventSub topics will be added.

**Comment by StimulCross** [comment]
@d-fischer  I will handle this one if you don't mind.

**Comment by iProdigy** [comment]
> One of the problems I'm noticing is that messages that are held back by automod are not shown to the streamer, even once they are approved! 

i'm unable to replicate this (but i tested without twurple)

**Comment by navarr** [comment]
> > One of the problems I'm noticing is that messages that are held back by automod are not shown to the streamer, even once they are approved! 
> 
> i'm unable to replicate this (but i tested without twurple)
> 

I have seen them start to come through (once approved) sometime after I wrote this message, so that at least is no longer a concern
