### ISSUE TITLE
EventSubChannelAdBreakBegin type not exported

### ISSUE THREAD

**Issue by theca11** [twurple/twurple#571]
## Bug Report

`EventSubChannelAdBreakBegin` type is not exported right now from package index. Submitting a PR now

### Expected behavior

Type is exported

### Actual Behavior

Type isn't exported

### Environment

- Version: v7.1.0
- Node version: v20.11
- Operating system: Win 10

**Comment by d-fischer** [comment]
Fixed in 31ebfb94.
