### ISSUE TITLE
Feat: Add EventSub Channel Points Automatic Reward Subscription Type

### ISSUE THREAD

**Issue by StimulCross** [twurple/twurple#582]
## Feature Request

[channel.channel_points_automatic_reward.add](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchannel_points_automatic_rewardadd)

**Comment by StimulCross** [comment]
I will handle this one

**Comment by ccKep** [comment]
Any ETA on merging this one? It would greatly help with the new Redemptions Twitch added and help make sure Bits can correctly be counted.
